### ISSUE TITLE
Not compatible with ItemPhysic + Gamerule

### ISSUE THREAD

**Issue by StiegeRobin** [MrCrayfish/MrCrayfishGunMod#1]
I installed this mod and now [ItemPhysic](https://github.com/CreativeMD/ItemPhysic) seems broken.

Also I'm missing a option to disable block damage from Grenade Launcher and Bazooka.
You could add one more gamerule for that like your gunGriefing-gamerule.

Mod version: 0.2.1-1.12.2
Forge version: 1.12.2-14.23.2.2611
ItemPhysic version: 1.4.12

**Comment by MrCrayfish** [comment]
Most likely because the library Obfuscate is conflicting. There is not a lot I can do because I use Obfuscate to render all the attachments onto weapons dynamically.
