### ISSUE TITLE
(1.12) Third-Person Animations Incompatible with Custom Model Armor

### ISSUE THREAD

**Issue by Noble772** [MrCrayfish/MrCrayfishGunMod#100]
When looking in third person while wearing any custom model armor, like Dragonskin or Dragonsteel Armor from Ice and Fire or Thaumcraft armor, the armor doesn't move with the animations making it so your arms stick out to hold the gun while the armor doesn't move.

**Comment by 16-squared** [comment]
Would this be an obfuscate bug?

**Comment by MrCrayfish** [comment]
1.12.2 is considered discontinued, as such I won't be fixing bugs.
