### ISSUE TITLE
Grenades and Grenade launchers don't do any destruction or damage despite being enabled

### ISSUE THREAD

**Issue by FilterUnfiltered** [MrCrayfish/MrCrayfishGunMod#108]
All in the title, bazookas work fine...

**Comment by FilterUnfiltered** [comment]
It seems that the bazookas don't do damage either (by the way by the damage I mean to me as the player and shooter, mobs do take damage)

**Comment by FilterUnfiltered** [comment]
Also how the heck do I craft the missiles for the bazooka? It doesn't see it in the workbench or crafting table

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishGunMod/commit/0e9a987b610bd339135e06a855d558775248cc11 and https://github.com/MrCrayfish/MrCrayfishGunMod/commit/eb930ce9ae0396763bb34935ec5522eac91f401c
