### ISSUE TITLE
[1.16.X] New gun animations don't render properly while sneaking

### ISSUE THREAD

**Issue by Ocelot5836** [MrCrayfish/MrCrayfishGunMod#111]
![image](https://user-images.githubusercontent.com/19599406/104828918-2f900780-5823-11eb-97ee-df0fac678a97.png)
![image](https://user-images.githubusercontent.com/19599406/104828920-33238e80-5823-11eb-8849-92688645dd53.png)
![image](https://user-images.githubusercontent.com/19599406/104828922-361e7f00-5823-11eb-833c-c8ce310ce91a.png)

**Comment by MrCrayfish** [comment]
Added intentionally to give steve a gamer neck. Will fix soon!

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishGunMod/commit/cc418a00d7defe89cf9243975f4ddcfd9ce6c411
