### ISSUE TITLE
Grenades and missiles do no damage when explosion radius is turned down.

### ISSUE THREAD

**Issue by eelvist** [MrCrayfish/MrCrayfishGunMod#112]
Loving this mod so far, excellent job. 

I configured explosions from grenades and missiles so that the radius is 0. I did this because I don't want greifing to be so easy on my server. Turning the explosion radius down also made it so that these weapons no longer do damage. If possible, I'd like to have separate sections in the configurations for the radius of damage and the radius of the explosion, that way they can still do damage to a wide area, but not destroy any blocks. Thank you for taking the time to read this, and once again, excellent job on this.

edit: Another problem I discovered recently is that you can reload while firing, allowing you to spam 'r' and basically not have to worry about taking the time to reload. If this is intentional, it should be configurable.

**Comment by MrCrayfish** [comment]
If the radius is zero, it won't do damage because it can't find players in an area of nothing. If you want to disable griefing, just diable gun greifing instead of the radius.
