### ISSUE TITLE
Gun Attachments rendering

### ISSUE THREAD

**Issue by Mr-Pineapple** [MrCrayfish/MrCrayfishGunMod#114]
After adding attachments to the guns they don't render correctly on the main body
Images: https://imgur.com/a/vq8LuUD

Forge Version: 35.1.4
Gun Mod Version: 1.0.0 BETA (Via Discord)
Obfuscate Version: 0.6.0-1.16.3

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishGunMod/commit/0c316166a118a8f3f6d84290693c806f4c9daafd
