### ISSUE TITLE
enchantments cause gun model to look a little weird (1.16)

### ISSUE THREAD

**Issue by shulkr** [MrCrayfish/MrCrayfishGunMod#115]
not the biggest thing but thought i'd make a report
https://media.discordapp.net/attachments/761239726022721576/807341108966588496/2021-02-05_15.03.27.png?width=837&height=471

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishGunMod/commit/ae2de55ec88eb5afa08376319efc20e7fcc83f0e
