### ISSUE TITLE
Bullet Knockback to Bosses in 1.16.4 Beta

### ISSUE THREAD

**Issue by johunter95** [MrCrayfish/MrCrayfishGunMod#118]
I've noticed that when firing any weapon with a high rate of fire, the continuous knockback from each bullet is able to completely stop the movement of mobs. While this isn't a problem for weaker mobs (because the usually die quickly), for mobs like the Ender Dragon or Wither, you are able to nearly stop their movement entirely, thus making the fight much easier than they should be. Also, while the Ender Dragon is on top of the Portal it is not immune to bullet damage (is usually immune to ranged damage in this phase). This also applies to the Wither in it's second phase.

**Comment by MrCrayfish** [comment]
Yeah the knockback issue is something I was never sure what to do. I wanted to keep vanilla bahaviour, however the high fire rate weapons do feel overpowered. Right now there is a config option to turn off knockback (See common > gameplay > enableKnockback). I will see what I can do to improve this.

For the dragon issue, I can problem implement a patch. Minecraft hardcodes arrows into the logic and not other projectiles.

**Comment by MrCrayfish** [comment]
The dragon's speed is also reduced when damaged, it's not just knockback causing the issue.

**Comment by MrCrayfish** [comment]
Closing. I've made some changes, the knockback strength of projectiles have been reduced and I've patched the dragon issue when it's hovering over the portal. https://github.com/MrCrayfish/MrCrayfishGunMod/commit/f999936366424b150dd290b58c3ce22afcc662b2 and https://github.com/MrCrayfish/MrCrayfishGunMod/commit/720385c0ad08a54815ff7b6a4b2755286c306708
