### ISSUE TITLE
1.0.0 version. light grip recipe not available

### ISSUE THREAD

**Issue by SEMODE** [MrCrayfish/MrCrayfishGunMod#120]
light grip recipe not available on workbench there are two specialized grip instead

https://giphy.com/gifs/minecraft-mrcrayfish-gun-mod-h8fdB1LCIsURRpge0q

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishGunMod/commit/03a039405c09d0ba5fedafb65c4e1892c2315131
