### ISSUE TITLE
Mod creating a conflict with shaders (problem with OpenGL error: 1282)

### ISSUE THREAD

**Issue by BlauUsagi** [MrCrayfish/MrCrayfishGunMod#121]
Mod running with shaders is creating a problem: OpenGL error: 1282. When the error occurs the whole character disapears, animation of character is invisible, screen is going white when shooting from a gun. When holding an item in hand, or dropped on the ground it goes invisible. No particles, entities or mobs are visible. 
Minecraft version: 1.16.4

**Comment by MrCrayfish** [comment]
Already patched in https://github.com/MrCrayfish/MrCrayfishGunMod/commit/57e532ccb209bd13afcf9c86fd246321bc8b5f55 but you should know that scopes won't work the same if shaders are enabled.
