### ISSUE TITLE
Open GL Error 1281

### ISSUE THREAD

**Issue by xDevillish** [MrCrayfish/MrCrayfishGunMod#122]
Whenever I play with the mod the character and hands and guns disappear? Please help!

**Comment by xDevillish** [comment]
After restarting the game my character came back but when I applied shaders I got error 1282 when zoomed in and 1284 when firing

**Comment by MrCrayfish** [comment]
Are you using the beta version? If so, download the full release.

**Comment by Sovthia** [comment]
I meet the same problem, shooting while screen shows some kind of texture file. And after that, all entities' models including players, animals, chests, and even my hands will disppear. Restart game or my PC cant sovle such problem. And I'm sure I installed the full release.

**Comment by Sovthia** [comment]
After uninstalling Optifine, mod just works properly.

**Comment by MrCrayfish** [comment]
Just Optifine things. I have fixed the error in recent versions but at the cost of preventing the scopes rendering their view.
