### ISSUE TITLE
Lenses and sensitivity

### ISSUE THREAD

**Issue by wallxnr** [MrCrayfish/MrCrayfishGunMod#126]
The aiming lenses are not zooming, as they are different lenses, each one should zoom differently right?
I would also like to see a blur in the background when opening the sight, to give more prominence where I am aiming, I believe, I would also like to ask to add a greater margin in the sensitivity of ADS or simply use the base sensitivity of the game as sensitivity of the sight.
To show what I said, I recorded a short video showing that the lenses do not zoom and how the sensitivity is low even at 1 (maybe because there is no zoom on the lenses). I uploaded it to GDrive.
https://drive.google.com/file/d/115YQBBIXlHzCF-YnFbyv2SevWkw8lwDM/view?usp=sharing

Also, if possible, could you add the option to customize the reticle of each lens ?

**Comment by MrCrayfish** [comment]
Remove shaders if you want the real scope experience, I literally had to break scopes so it wouldn't spit out errors.  ADS sensitivty in mouse controls menu.

**Comment by MrCrayfish** [comment]
FOV is probably being modifed by another mod, preventing the gun mod from working.
