### ISSUE TITLE
Latest update crashing multiplayer server on startup

### ISSUE THREAD

**Issue by OmnipresentMicroorganism** [MrCrayfish/MrCrayfishGunMod#129]
I have a modpack containing CGM. The modpack works fine in singleplayer worlds, but when I attempt to launch my server with the modpack it crashes the server. Attached is the crashlog generated by the server.

[crash-2021-02-26_07.29.57-server.txt](https://github.com/MrCrayfish/MrCrayfishGunMod/files/6050043/crash-2021-02-26_07.29.57-server.txt)

**Comment by glyyf** [comment]
I've received the same error running 15.2, using cgm-1.0-1.15.2.jar

[crash-2021-04-27_14.01.57-server.txt](https://github.com/MrCrayfish/MrCrayfishGunMod/files/6387036/crash-2021-04-27_14.01.57-server.txt)

**Comment by PGgamer2** [comment]
I have the same issue
[crash-2021-06-25_22.39.56-server.txt](https://github.com/MrCrayfish/MrCrayfishGunMod/files/6721317/crash-2021-06-25_22.39.56-server.txt)
If I use an older version of the mod (0.16.1) the dedicated server works fine

**Comment by MrCrayfish** [comment]
Closing since I believe I fixed this and no one uses 1.15.2 anymore.
