### ISSUE TITLE
Stun Grenade missing from the Workbench [Gun Mod 0.9.2]

### ISSUE THREAD

**Issue by fandomaniac** [MrCrayfish/MrCrayfishGunMod#13]
I see the Stun Grenade in JEI, but it does not appear in the Workbench, 

Mod Version: Gun Mod 0.9.2
Forge Version:  Forge-1.12.2 - 14.23.5.2769

**Comment by MrCrayfish** [comment]
Cheers. Will fix soon!

**Comment by MrCrayfish** [comment]
Marking as fixed
