### ISSUE TITLE
Visual bug on scope

### ISSUE THREAD

**Issue by Sahz23** [MrCrayfish/MrCrayfishGunMod#134]
I have this visual bug that happens on large and medium scopes help
![image](https://user-images.githubusercontent.com/80552487/111009166-76e4d100-8358-11eb-888a-e7eef0fd94ea.jpg)

**Comment by xToastGhost** [comment]
i have the same problem

**Comment by MrCrayfish** [comment]
Are you using Optifine?

**Comment by OsuAims** [comment]
I have the same issue, and i do use optifine as well

**Comment by DaKoolDude** [comment]
I've got the same problem with the scopes and I use optifine as well

**Comment by MrCrayfish** [comment]
Does the problem occur without Optifine?

**Comment by KatazGuy** [comment]
I have the same problem but i am not using optifine

**Comment by SCroutSoup** [comment]
I tried navigating to options>video settings>shaders and set it to off, worked for me
I also use optifine.

**Comment by ghost** [comment]
I have also experienced this issue. Oddly I can still see Mekanism Logistical Transporters but everything else appears black. This is using cgm-1.0.1-1.16.3 with Forge 1.16.5-36.1.24. I do not have Optifine installed.
![2021-05-23_20 40 38](https://user-images.githubusercontent.com/84690118/119282456-b9a01080-bc07-11eb-9099-eacc44c73c51.png)

**Comment by GunnKing5** [comment]
i had the almost everything black issue, i use optifine and changed from faboulus to fancy

**Comment by PNOAGAMER** [comment]
Anyone find any solution? I'm having the same issue.

**Comment by MrCrayfish** [comment]
Do you have the issue when only the Gun Mod is installed?

**Comment by MrCrayfish** [comment]
This will be fixed in 1.3.0

**Comment by JustEnotik** [comment]
THANK U!

**Comment by Dark-Hunter-04** [comment]
Same problem, can you fix it in 1.12.2 too? Thanks :)

**Comment by matveijunosha-prog** [comment]
> This will be fixed in 1.3.0
Can you pls win it on 1.12.2 and update pls if you can
