### ISSUE TITLE
Workbench doesn't drop when broken.

### ISSUE THREAD

**Issue by DawnXVI** [MrCrayfish/MrCrayfishGunMod#136]
I'm on 1.16.4 using the 1.16.3 version of the mod, and I'm not sure if that's what's wrong, or if this is intentional, or not, but the workbench doesn't drop after I break it. It happened once when I broke it with an iron pick so I could move on and keep exploring to find more iron. I thought it was just some weird one-time glitch and I was pretty annoyed by it. But then I placed it again later to craft a Pistol, and after breaking it, it still didn't drop. Thinking about it, I remember using this mod with friends on 1.12.2 a long while ago so I know it's supposed to drop when you break it. Is it maybe some other mod I have installed? Can anyone help?

**Comment by WrongWeekend** [comment]
This happens for me as well, using version cgm-1.0.1-1.16.3.jar on MC version 1.16.5.

**Comment by MrCrayfish** [comment]
Fixed in @Ocelot5836 PR
