### ISSUE TITLE
All weapons have an enchantment glint by default even when not enchanted?

### ISSUE THREAD

**Issue by Neko2n** [MrCrayfish/MrCrayfishGunMod#143]
![image](https://user-images.githubusercontent.com/43053729/112741129-78f18700-8f37-11eb-932d-b273cd53709b.png)
That's really all I can give for this issue. I don't think this is supposed to be a default thing, as it looks really weird and the enchantment glint kind of blocks the colors of dyes when applied to weapons. If it is a default thing, PLEASE make this configurable.

Edit: actually I could probably mention I'm using 261 other mods. That might be important. Logs, mod list, etc can be provided upon request if needed, though I'm not seeing anything related to CGM in my latest.log.

**Comment by MrCrayfish** [comment]
I can definitely say this is not normal. Can you try an isolated test? Does this only show in creative? Do the items have an NBT tags on them?

**Comment by MrCrayfish** [comment]
It looks like another mod causing the issue since I can clearly see that the enchanted books have extra rendering (some sort of letter). I'd uninstall that mod.

**Comment by Neko2n** [comment]
I'll try to narrow down the mod causing this, as this issue doesn't seem to happen with any other mods. This "enchanted unenchanted item" bug seems to only have appeared for your items, and only the guns from this specific mod too. If it's not an interaction caused on your end though, I'll definitely be uninstalling the mod causing this lmao.

**Comment by Neko2n** [comment]
Found the culprit: https://www.curseforge.com/minecraft/mc-mods/improved-mobs 
Is there any way for this to be fixed on your end? I was actually using this mod for a few useful features like automatic villager targeting for most mobs and armor spawning integration. If not, I'll probably be fine removing it or bringing this issue up on the mod's github.

**Comment by MrCrayfish** [comment]
I don't really know what to "fix" if it was something I could do on my end. I'd suggest bringing it up to the other developer, maybe they know more about why it might be happening (I'm not sure if they are touching anything related to enchantments). I'll be happy to find a solution if they are touching enchantments or something related to rendering the glint effect on items.

**Comment by MrCrayfish** [comment]
Loaded up the mods you mentioned, no issues ¯\_(ツ)_/¯
![image](https://user-images.githubusercontent.com/4958241/113283849-5ba22b80-9330-11eb-9e6e-71e652f7060d.png)

**Comment by MrCrayfish** [comment]
Just to rule out optifine, loaded up game again without Optifine.
![image](https://user-images.githubusercontent.com/4958241/113284259-eaaf4380-9330-11eb-8e3b-3f974c5545b4.png)

**Comment by Neko2n** [comment]
It was probably a configuration file change or a corrupted file then. Removing the mod fixed the issue for me, and adding it back brought back the issue; running an instance with just CGM and Improved Mobs also had the issue. I'll go ahead and close the issue for now, since it most likely has nothing to do with your mod in this case.
