### ISSUE TITLE
Can not hit Enderman

### ISSUE THREAD

**Issue by RuggedTime** [MrCrayfish/MrCrayfishGunMod#144]
![image](https://user-images.githubusercontent.com/46664847/112971159-87cb7a00-9181-11eb-9542-8d749b911ed9.png)
The picture saysI have ability to headshot any vanilla mob in the game，but I can't shoot enderman, is this a bug ?

**Comment by MrCrayfish** [comment]
Not a bug, enderman are immune to any projectiles; much like arrows

**Comment by RuggedTime** [comment]
WOW......thanks!
