### ISSUE TITLE
Incompatibility with "BigBrain"

### ISSUE THREAD

**Issue by Erysch** [MrCrayfish/MrCrayfishGunMod#145]
Using MrCrayfish's Gun Mod with BigBrain causes the ADS-Sensitivity (Gun Mod) setting to not affect anything anymore. It seems that it is always set to 1, even though the default value is 0.75.

I found this issue while creating a modpack. To ensure it's not caused by other mods I created a pack with only these two mods inside and this issue still appears.

**Comment by MrCrayfish** [comment]
BigBrain cancels the player updatePlayerLook method and locks out other mods. https://github.com/seymourimadeit/Big-Brain/blob/main/src/main/java/tallestegg/bigbrain/mixins/MouseHelperMixin.java#L42

**Comment by MrCrayfish** [comment]
I'd suggest they look at my solution to modifying sensistivity that respects other mods that may modify it too.

**Comment by NighthowlerStudios** [comment]
They applied this solution on a recent update.  Just a notification about this.  ADS has been functional for a couple weeks now.  I had submitted the same bug report to them and they realized and fixed it.

**Comment by Erysch** [comment]
> They applied this solution on a recent update. Just a notification about this. ADS has been functional for a couple weeks now. I had submitted the same bug report to them and they realized and fixed it.

Hey, thanks for the tip. :)
