### ISSUE TITLE
enchantments through commands

### ISSUE THREAD

**Issue by erikundel** [MrCrayfish/MrCrayfishGunMod#146]
If you want to enchant weapon through "/enchant playername enchantment lvl" command you can easily do this, but using giving already enchanted item isnt working, like this: "/give @p crossbow{Enchantments:[{id:multishot,lvl:1}]}", with modded enchantments, this will make your weapon glow, but nothing else will happened
a little vid bout it: https://youtu.be/spUQoRUySe0

**Comment by MrCrayfish** [comment]
It's not `id:accelerator`, it's `id:"cgm:accelerator"`
