### ISSUE TITLE
Guns Delayed While Being Shot in the Nether and End

### ISSUE THREAD

**Issue by Nether-Beast72** [MrCrayfish/MrCrayfishGunMod#149]
So after trying out Mr. Crayfish's Gun Mod, I decided to take another step and try to use them in the nether and the end dimensions. But what I have stumbled upon may be a massive bug. When I attempted to use my bazooka in the nether, for some reason the projectile didn't explode. I shot another rocket. Then the animation for the first rocket decided to loop over and over constantly. After 5 seconds the rocket finally exploded. I tested this in the End too, and what do ya know? Same issue. The animation showed a rocket no-clipping through an obsidian pillar in the end. Also when I shoot the dragon it causes some lag in game.

**Comment by 16-squared** [comment]
Problem did not occur on my end.

**Comment by MrCrayfish** [comment]
I can't seem to reproduce. Feel free to open a new issue if still a problem on the latest version of the mod.
