### ISSUE TITLE
Advanced Ammo only works with a regular rifle

### ISSUE THREAD

**Issue by fandomaniac** [MrCrayfish/MrCrayfishGunMod#15]
Advanced Ammo only works on a basic rifle on both siingle-player survival and SMP. 

Mod Version: Gun Mod 0.9.2
Forge Version: Forge-1.12.2 - 14.23.5.2769

**Comment by MrCrayfish** [comment]
I'm confused. That's how it's suppose to work. The rifle uses advanced ammo.

**Comment by fandomaniac** [comment]
I'm sorry. I didn't know.
