### ISSUE TITLE
Enchants not being configurible

### ISSUE THREAD

**Issue by Ventago** [MrCrayfish/MrCrayfishGunMod#151]
I've Been Looking through the config files and i couldn't find anything about the enchants. I want to be able to have the quick hands enchant with overcapacity in the same weapon but because there is no config for it I can;t.

**Comment by MrCrayfish** [comment]
It's not an option, they are mutually exclusive enchantments. Just like how on a Sword you have to pick between Smite, Sharpness, or  Bane of Arthropods.
