### ISSUE TITLE
Ammo cost possible issue

### ISSUE THREAD

**Issue by VariantMouse** [MrCrayfish/MrCrayfishGunMod#153]
Not sure if it's a bug or a feature, but it's kinda driving me up a wall:
When crafting ammo, the Advanced bullet costs 1 gunpowder and 4 iron nuggets for 16 rounds, but the basic bullet costs 2 gunpowder and 8 iron nuggets for 32 rounds, which means that from a pure ratio standpoint, the advanced bullet and the basic bullet have the same cost, which seems incorrect.

Again, not sure if this is working as intended or not, just thought I'd throw it out there.

**Comment by MrCrayfish** [comment]
I don't know where you got those numbers, as of right now these are the recipes:

**Basic bullet:** 4 iron nuggets, 1 gunpowder for 32 bullets
**Advanced:** 4 iron nuggets, 1 gunpowder for 16 bullets

**Comment by MrCrayfish** [comment]
If you're using an old version (less than 1.15) than I won't be fixing.
