### ISSUE TITLE
Can you change the cost somewhere? 

### ISSUE THREAD

**Issue by Erysch** [MrCrayfish/MrCrayfishGunMod#154]
Thank you for much for this mod!

Is there a way to change the cost of the weapons or even the materials (like using Steel from Mekanism/AllTheOres)?
The weapons are pretty strong and easy to get early game. I had guns before I had a bow. (:

**Comment by winsrp** [comment]
I was about to come and ask for the same thing, I would like to change the material used to create guns and ammo, plus the amount of ammo created on each recipe. The mod is great but it seems too OP for survival adventure.

For example, weapons made of steel, bullets made with lead nuggets and copper nuggets, and advanced bullets, made with lead nuggets copper nuggets and steel nuggets for example, and that each recipe yields only 1 or 2 bullets a a time max.

I tried with craft tweaker but that doesn't seem to be working.

Thanks a lot for a great mod.

**Comment by Autovw** [comment]
You can do this by creating a datapack.
I'd suggest to look up a tutorial for this on YouTube since it's fairly easy to do.

**Comment by winsrp** [comment]
Oh! I will give it a check this weekend and report back if I'm so dumb that I cannot get it to work. Tx

**Comment by winsrp** [comment]
seems like I managed to make it work but only if I use a specific material such as mekanism:nugget_steel, but I cannot use a more generic forge:nuggets/steel, so I cannot use the immersive engineering nuggets as replacement, does anyone know how I can use the generic type for nuggets instead of a specific one?

**Comment by Erysch** [comment]
Can you show me the syntax

**Comment by Autovw** [comment]
> seems like I managed to make it work but only if I use a specific material such as mekanism:nugget_steel, but I cannot use a more generic forge:nuggets/steel, so I cannot use the immersive engineering nuggets as replacement, does anyone know how I can use the generic type for nuggets instead of a specific one?

Replace "item" with "tag" then it should work.

**Comment by Erysch** [comment]
> seems like I managed to make it work but only if I use a specific material such as mekanism:nugget_steel, but I cannot use a more generic forge:nuggets/steel, so I cannot use the immersive engineering nuggets as replacement, does anyone know how I can use the generic type for nuggets instead of a specific one?

nice one! Would you show me the code of it to see the syntax? 👀

**Comment by winsrp** [comment]
> > seems like I managed to make it work but only if I use a specific material such as mekanism:nugget_steel, but I cannot use a more generic forge:nuggets/steel, so I cannot use the immersive engineering nuggets as replacement, does anyone know how I can use the generic type for nuggets instead of a specific one?
> 
> Replace "item" with "tag" then it should work.

Thanks for the tip, I'm not at home right now but once I'm back I'll give it a try and post the whole thing here with some details

**Comment by winsrp** [comment]
Using tag or item just makes the recipe disappear from the table seems like it doesn't like it, any other ideas?

**Comment by Erysch** [comment]
Does anyone tried with crafttweaker or does it not work? It's hard to find there some information about syntax for the newest version.

**Comment by winsrp** [comment]
Haven't tried that but the data pack is easy to make, one already comes inside the mod file. Just open the jar as a zip, and check the data folder, all that folder is actually a data pack that can be almost copy pasted an modified.

**Comment by winsrp** [comment]
I just need to have that tag working to use forge items instead of specific mod items

**Comment by Erysch** [comment]
> Haven't tried that but the data pack is easy to make, one already comes inside the mod file. Just open the jar as a zip, and check the data folder, all that folder is actually a data pack that can be almost copy pasted an modified.

Oh thanks, that seems to be doable!

**Comment by Erysch** [comment]
> I just need to have that tag working to use forge items instead of specific mod items

I had the same problem with crafttweaker. It seemed that you had to predefine the tags. Maybe you have to do that too, which would be annoying imo.

**Comment by Autovw** [comment]
> I just need to have that tag working to use forge items instead of specific mod items

Well, if that doesn't work you'll have to show the code so I can take a look at it.

**Comment by winsrp** [comment]
> > I just need to have that tag working to use forge items instead of specific mod items
> 
> Well, if that doesn't work you'll have to show the code so I can take a look at it.

Here you go

{
  "type": "cgm:workbench",
  "result": {
    "item": "cgm:basic_bullet",
    "count": 1
  },
  "materials": [
    {
      "tag": "forge:nuggets/steel",
      "count": 1
    },
    {
      "item": "minecraft:gunpowder",
      "count": 1
    }
  ]
}

the basic bullet just disappears from the bench

**Comment by Autovw** [comment]
> Here you go
> 
> {
> "type": "cgm:workbench",
> "result": {
> "item": "cgm:basic_bullet",
> "count": 1
> },
> "materials": [
> {
> "tag": "forge:nuggets/steel",
> "count": 1
> },
> {
> "item": "minecraft:gunpowder",
> "count": 1
> }
> ]
> }
> 
> the basic bullet just disappears from the bench

After messing around with it myself, I can't get it to work either. :(
It might still be possible but I have 0 experience with the mekanism mod so I'm afraid I can't help you further.

**Comment by winsrp** [comment]
Could it be that the mod itself needs a specific item and it doesn't accept tags? Or doesn't know how to accept tags?

**Comment by Autovw** [comment]
Could be, but I really don't know if it's mekanism or gun mod's fault.

**Comment by winsrp** [comment]
Well I think it has nothing to do with mekanisn, using the makenism item does work and using the immersive engineering item does work but using the forge tag does not.

**Comment by Erysch** [comment]
Did you try items:forge:nuggets/steel ?

**Comment by Erysch** [comment]
> > > I just need to have that tag working to use forge items instead of specific mod items
> > 
> > 
> > Well, if that doesn't work you'll have to show the code so I can take a look at it.
> 
> Here you go
> 
> {
> "type": "cgm:workbench",
> "result": {
> "item": "cgm:basic_bullet",
> "count": 1
> },
> "materials": [
> {
> "tag": "forge:nuggets/steel",
> "count": 1
> },
> {
> "item": "minecraft:gunpowder",
> "count": 1
> }
> ]
> }
> 
> the basic bullet just disappears from the bench

Did you try "tag": "items:forge:nuggets/steel" ?

**Comment by Erysch** [comment]
I guess you should just add an easy way to put the steel nuggets in the crafting table to convert them to another steel nugget. Like from immersive enginerring to mekanism, and then just add the mekanism steel nugget as a price for the basic bullets e. g.
That's how I will do it

**Comment by winsrp** [comment]
mekanism has a block called the oredictionary something, I don't remember right now, that does just that, converts one item from one mod to the same item from another mod, in this case it will be other mods steel, to mekanism steel, so no need to do anything extra, but it would be nice to have the option to use tags, so that we don't need the workaround.
