### ISSUE TITLE
Iron Golems start attacking me for no reason after shooting any gun at any direction

### ISSUE THREAD

**Issue by iSyriux2** [MrCrayfish/MrCrayfishGunMod#157]
Frequency: Always
Annoyance: Big, seeing as I'm playing an apocalypse survival map and I use the guns to shoot parasites, and the iron golems serve as mecha guards to assist me

https://user-images.githubusercontent.com/62969957/115476435-da8fd300-a20f-11eb-9df3-f33ea90be17b.mp4

**Comment by MrCrayfish** [comment]
It's not intentional but simply guns make mobs panic. Unfortunately I don't maintain the 1.12 version anymore so it's unlikely that I'll fix it in that version.
