### ISSUE TITLE
Scopes are not working when using shaders.

### ISSUE THREAD

**Issue by Kohxax** [MrCrayfish/MrCrayfishGunMod#158]
![2021-04-22_21 52 16](https://user-images.githubusercontent.com/75534175/115717398-1adc8600-a3b5-11eb-9dfc-d9b02f444913.png)
![2021-04-22_21 52 01](https://user-images.githubusercontent.com/75534175/115717426-20d26700-a3b5-11eb-8f39-5f79906818aa.png)

I am using SEUS renewed v1.0.1.
Scopes are not working with using shaders.
I tried it with several other shaders besides SEUS, but they all failed.

Minecraft ver  : 1.16.5

Forge ver  : forge-1.16.5-36.1.6

Mod list :
cgm-1.0.1-1.16.3
cloth-config-4.11.19-forge
DynamicSurroundings-1.16.4-4.0.4.1
forgemod_VoxelMap-1.10.12_for_1.16.5
jei-1.16.5-7.6.4.87
obfuscate-0.6.0-1.16.3
OptiFine_1.16.5_HD_U_G7

**Comment by MrCrayfish** [comment]
I won't go into details but shaders just render different that breaks scopes. I actually added a fix so scopes would some what work when using shaders but it just won't render the world inside the scope. I won't be fixing, sorry.

**Comment by Kohxax** [comment]
OK, keep up the good work on the mod production !
Thank you for your response.

**Comment by NighthowlerStudios** [comment]
I found shaders to be mostly working until you teleport dimensions.  If you reload the client, the error seems to clear.  This only happens for me in modded dimensions.  

Using BSL 8.0.0.1 and Optifine G7.
