### ISSUE TITLE
Vivecraft incompatibility (mod v.1.01)

### ISSUE THREAD

**Issue by TheSpiderDungeon** [MrCrayfish/MrCrayfishGunMod#159]
Took a while to weed out the culprit of the crashes, but I found that this is the mod that did it. Super unfortunate because I really wanted to use this mod in VR - though thinking back, I can see why that might not have been possible.

Still, crash log [here](https://pastebin.com/3LmUTqqT), if you ever feel like you want to add compatibility. I'm sure nobody will complain. Awesome work btw, I love how you do the item crafting in your mods :)

**Comment by MrCrayfish** [comment]
Even if I fix this, the mod doesn't work in VR as you expect it would.
