### ISSUE TITLE
[issue 1.6.5 - cgm 1.0.1] Cannot use tags in recipe datapacks

### ISSUE THREAD

**Issue by winsrp** [MrCrayfish/MrCrayfishGunMod#162]
cgm-1.0.1-1.16.3

While tying to make a new data pack, I can change the item to a specific mod item, but I cannot use tags from forge.

e.g. 

Here I'm trying to use the forge:nuggets/steel, and it doesn't accept that.

```
{
  "type": "cgm:workbench",
  "result": {
    "item": "cgm:basic_bullet",
    "count": 1
  },
  "materials": [
    {
      "tag": "forge:nuggets/steel",
      "count": 1
    },
    {
      "item": "minecraft:gunpowder",
      "count": 1
    }
  ]
}
```

**Comment by MrCrayfish** [comment]
Added in https://github.com/MrCrayfish/MrCrayfishGunMod/commit/c22006108dcef19f1e1fc2afb37b2d38832aafec
Coming in the next update
