### ISSUE TITLE
[issue 1.6.5 - cgm 1.0.1] breaking the workbench returns nothing

### ISSUE THREAD

**Issue by winsrp** [MrCrayfish/MrCrayfishGunMod#164]
Mods:
forge-1.16.5-36.1.4
cgm-1.0.1-1.16.3
obfuscate-0.6.0-1.16.3

So I put down a workbench and when I try to break it with

Empty hand = nothing
Axe = nothing
shovel = nothing
pickaxe = nothing
hoe = nothing

is there a way to pickup this workbench up without destroying it?

can anyone else confirm.

tx.

**Comment by Autovw** [comment]
This issue has been fixed a while ago, but I guess Cray hasn't released the update yet... ¯\_(ツ)_/¯

**Comment by RepeatGitHub** [comment]
I might make a datapack to make a loot table for the workbench, but knowing me it probably won't work lmao

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishGunMod/commit/5e89fecccd61f04eabf45bedf87234839a3df269
