### ISSUE TITLE
[issue or suggestion?] Weapons cannot have more than 3 enchantments

### ISSUE THREAD

**Issue by winsrp** [MrCrayfish/MrCrayfishGunMod#166]
So, a weapon can only have a max of 3 enchantments, which is kind of odd, if this is the intended behavior, can we have a config option to set the max amount of different enchantments to be had on a weapon?

**Comment by MrCrayfish** [comment]
Guns can only have up to three enchantments, this is to encourage experimenting with enchantment combinations and to have a reason to craft more than one of the same weapon type.

**Comment by winsrp** [comment]
I understand that, but on our server, mobs can get really really difficult, to the point that a maxed minigun cannot kill a mob even with 1000 rounds, so we need a bit more punch, so that's why I would have loved to have a config option, as to not change that for everyone XD

**Comment by MrCrayfish** [comment]
May I suggest creating a datapack that increases the stats of weapons?

**Comment by winsrp** [comment]
Actually we tested that already but difficulty increases with time on the server, so after testing a bit we did increase damage but just a bit and we did tweaked some of the recipes to make it a bit more hard to get the weapons. 

If damage is increased too much and you got the weapons too soon you are overpowered for the rest of the game and loses the fun of it. 

We also have apotheosis mod which tweaks the way you get enchantments to make it a bit harder but also it gives the possibility of increased the enchant levels, cool but you have to work for them, which seems rewarding, and you need to gear ready to go ASAP, so we manage to find ways to automate making bullets with harder recipes.

E.g. Since we have immersive engineering (ie), a single bullet costs one bullet casing (from ie), a lead nugget and 1 gunpowder. One advanced bullet adds 1 steel nugget to the previous recipe. So the game is hard but with only 3 enchants it's seems like you stop having room to grow on that one weapon you like, so we carry several different types of weapons for different scenarios, and not several of the same weapon. Your mod is awesome!

Sorry for the long read, hopping you reconsider. Tx so much for your time.
