### ISSUE TITLE
Grenade Launcher Capacity

### ISSUE THREAD

**Issue by 16-squared** [MrCrayfish/MrCrayfishGunMod#167]
In the game, the grenade launcher has a capacity of 1 grenade. However, the launcher is clearly based off of a design capable of holding six. I believe that increasing the capacity would also improve gameplay balance.

**Comment by FenzDev** [comment]
you can change that via overwriting the gun's data file ("data/cgm/guns/grenade_launcher.json")

```json
{
   "general" : {
      ...
      "maxAmmo": 6,
      ...
   }
   ...
}
```

**Comment by 16-squared** [comment]
Thanks
