### ISSUE TITLE
fix naming of certain items

### ISSUE THREAD

**Issue by 16-squared** [MrCrayfish/MrCrayfishGunMod#168]
the "scope" group of attachments has some parts named incorrectly. The "short scope" would better be named a holographic sight or a reflex sight. The "medium scope" could either be a scope or an ACOG sight, depending on your intent. Scopes have magnification written as a ratio, such as 3x or 6x. 

There are other parts named inaccurately, such as the "specialized grip", which actually is a Vertical Fore Grip (and can be attached to some submachine pistols, such as later versions of the Uzi).

**Comment by MrCrayfish** [comment]
One thing to know about this mod is that it's not trying to be realistic. Just because there is a similar real life equivalent doesn't mean I have to name it the same. It's much more fun creating an arcade gun mod.

**Comment by 16-squared** [comment]
Fair point.
