### ISSUE TITLE
PIgman and Enderman

### ISSUE THREAD

**Issue by chaosnick44** [MrCrayfish/MrCrayfishGunMod#173]
Hello! When i shoot near a pigman or enderman they get agressiv. (i dont shoot them) Pls fix it its annoying. Bye

**Comment by EnderiteFox** [comment]
It is because they are panicking due to the noise, use a silencer to reduce the area where neutral mobs are panicking

**Comment by Ch1216** [comment]
Does this still happen?, ive tested it and they dont seem to be agressive

**Comment by MrCrayfish** [comment]
Duplicate of https://github.com/MrCrayfish/MrCrayfishGunMod/issues/163
