### ISSUE TITLE
Gun mod - Medium & Large scopes show white when zoomed in

### ISSUE THREAD

**Issue by matt1945ayye** [MrCrayfish/MrCrayfishGunMod#174]
The title says it all.
https://user-images.githubusercontent.com/84905533/119803464-c494c280-bedf-11eb-98e7-1227d9fc8399.png

**Comment by VikranthMallru** [comment]
Hi matt, if you have optifine, it will show white when zoomed in. I faced the same problem but when i removed optifine, it all worked perfectly fine.

**Comment by vsvetoslavov** [comment]
Any chance to make this work with optifine? Or some workaround - i.e. using specific shader, or settings or whatever.

**Comment by VikranthMallru** [comment]
I don't think so, maybe contact crayfish himself!

> Any chance to make this work with optifine? Or some workaround - i.e. using specific shader, or settings or whatever.

**Comment by 16-squared** [comment]
Like most Optifine-related problems, it does not happen on my end (Yes, I have optifine as a forge mod)

**Comment by NighthowlerStudios** [comment]
specific shaders will cause this.  the only ones I am aware of that don't are BSL and Complementary

**Comment by NighthowlerStudios** [comment]
you also need to make sure texture transparency is on, I'm seeing you have a ton of graphical options turned off.

**Comment by MrCrayfish** [comment]
Duplicate of https://github.com/MrCrayfish/MrCrayfishGunMod/issues/134
