### ISSUE TITLE
Minigun Model not showing up in-game but still shows up on the workbench

### ISSUE THREAD

**Issue by DaBakedPotatoBoi** [MrCrayfish/MrCrayfishGunMod#175]
![2021-05-28_21 33 19](https://user-images.githubusercontent.com/84976158/119991737-598cde00-bffc-11eb-9f36-2a5bd969ddc7.png)

**Comment by 16-squared** [comment]
possible conflict with other mods? try removing them and see if that fixes it(try to determine which specific mod is causing the problem).

**Comment by MrCrayfish** [comment]
There was a recent issue with Fabulous graphics settings causing weapons not to render. Change it to Fancy or Fast for a temporary fix. If this doesn't fix it, create a new issue.
