### ISSUE TITLE
Network Disconnect: Server Mod rejections: MrCrayfish's Gun Mod: Requires version 0.15.3 but client has 0.12.2.

### ISSUE THREAD

**Issue by melerodev** [MrCrayfish/MrCrayfishGunMod#177]
Hello. I have added MrCrayfish's Gun mod on my Aternos server and I get the following error:
Network Disconnect: Server Mod rejections:
MrCrayfish's Gun Mod: Requires version 0.15.3 but client has 0.12.2.
I have installed the forge version 1.12.2 (14.23.4.2766)
Any help.

**Comment by MrCrayfish** [comment]
I mean pretty easy fixed. Install the 0.15.3 version...

**Comment by melerodev** [comment]
No version 0.15.3.
@MrCrayfish 
![image](https://user-images.githubusercontent.com/80626286/120342909-8856cd00-c2f8-11eb-862b-48f9dca58dbd.png)

**Comment by MrCrayfish** [comment]
I don't even know what you're showing me. You need to install the Gun Mod 0.15.3 on your client.

**Comment by MrCrayfish** [comment]
https://mrcrayfish.com/mods?id=cgm

**Comment by melerodev** [comment]
Okay. Resolvel the problem. 10/10
