### ISSUE TITLE
Can't add scopes

### ISSUE THREAD

**Issue by Nemmos** [MrCrayfish/MrCrayfishGunMod#182]
Hey ! I have a problem with the scopes. I can craft them without worrying about survival or having them in creative, but when I want to assemble them on my weapons with a crafting table, nothing happens. I tried a lot of combinations but no way to add a scopes on my weapons. I am in 1.16.5 with forge 1.16.5 - 36.1.30 and gun mod in 1.0.1. Do you know how to solve the problem? Thanks !
(excuse me for my english, i'm french lol)

**Comment by 16-squared** [comment]
Don't use a crafting table, open the weapon's attachments menu.
