### ISSUE TITLE
I can't aim and I can't shoot auto

### ISSUE THREAD

**Issue by 99DarkSun66** [MrCrayfish/MrCrayfishGunMod#185]
It does not let me aim and I can only shoot in manual it does not let me shoot in automatic

**Comment by 16-squared** [comment]
Are you sure that the weapon you are using is capable of automatic fire?

**Comment by 99DarkSun66** [comment]
Yes, because I tried all the weapons and it only worked in manual

**Comment by ghost** [comment]
Which weapon does not work in automatic?
