### ISSUE TITLE
[Suggestion] Earmuffs and deafening

### ISSUE THREAD

**Issue by DeckerExpert** [MrCrayfish/MrCrayfishGunMod#186]
**Description of the Suggestion**
Adds an item called Earmuffs. 
When not worn, the shooter will get the deafening effect for configurable amount of time with the default being 15 seconds. The shooter will get this effect every configurable amount of bullets shot, with the default being 25-30. 
However, when the shooter is wearing earmuffs, they will not get the effect and are immune to the deafening effect from stun grenades, but their volume will then be decreased to a configurable amount, with the default being 65-50%. Earmuffs can be disabled in the configs.

**Comment by MrCrayfish** [comment]
Unlikely to add. I think the flash grenade just needs to be rebalanced. I personally think it's too long on a direct hit.
