### ISSUE TITLE
Workbench recipes do not appear to be overwritable by datapacks

### ISSUE THREAD

**Issue by Fisk24** [MrCrayfish/MrCrayfishGunMod#187]
By creating a datapack with the exact file name and directory structure as the source recipes, One would expect that the original recipe would be overwritten and replaced by the one in the datapack. However in my testing it appears that I instead end up with two recipes, the original unchanged recipe AND the new modified recipe. This makes it impossible to modify this mods crafting recipies without using some other tweaking mod. 

I have used the /reload command, and I've even tried completely restarting the game.

My datapack file structure is as follows:

    data/recipes/advanced_bullet.json 

And the source code file structure under "generated/resources" is:

    data/recipes/advanced_bullet.json

Ive checked and triple checked for spelling mistakes, I even tried downloading the original json file from this repo so i could be sure that the file is named correctly. I still get two recipes.

Minecraft logs in multimc reveal that there are apparently no json parsing issues.

Steps to reproduce:
Create a datapack with the correct directory structure.
copy advanced_bullet.json from this repo, and change any of the constituent ingredients (I used oak_log instead of nuggets to make it very obvious)
/reload in game to reload the datapacks
check workbench, there will now be two recipes for advanced bullets.

**Comment by MrCrayfish** [comment]
It's `data/cgm/recipes/advanced_bullet.json`
