### ISSUE TITLE
Other entities getting angry while shooting near them

### ISSUE THREAD

**Issue by pvtBlazingDeck** [MrCrayfish/MrCrayfishGunMod#189]
i am reporting a bug for the gun mod from mr.crayfish

hello i made a server on aternos and added your 3 mods to it and me and my friend were playing on it everything was good but,
right after we entered the neather to get blaze rods we were shooting the blazes with the assult rifle but suddenly the pigmen came to attack us even though we didn't hit them once same happend in the end when we were hitting the dragon the enderman came to attack us even though we didnt hit or look at them

if you can please fix this bug,  if you want to ask anymore questions then u can add me on discord my id is Blazing Deck#7589

thanks for reading this

**Comment by Autovw** [comment]
That's not a bug, it's a feature.

It's called "Mob Agro" which can be turned off in the config.
If you want to turn it off go into the the config folder of your server and open the file called ``cgm-common.toml`` and under ``[common.aggro_mobs]`` set ``angerHostileMobs = false``.

**Comment by MrCrayfish** [comment]
You can also exempt entities if you don't want to disable everything.
