### ISSUE TITLE
Cinematic camera will not turn off or on in certain cases

### ISSUE THREAD

**Issue by KingParity** [MrCrayfish/MrCrayfishGunMod#19]
when switching between guns in third person, the cinematic camera will not turn off or on if you switch between a bazooka and a different gun. This will update when you go back into first person

**Comment by MrCrayfish** [comment]
Thanks for the report. Will look into it!

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishGunMod/commit/f284dc469cbb31a0d7b42b2a74f715d6e924451a
