### ISSUE TITLE
1.16.5 workbench

### ISSUE THREAD

**Issue by JamesX257** [MrCrayfish/MrCrayfishGunMod#192]
For some unknown reason, when i try to interact with the workbench in survival mode, nothing happens. I can't even make a gun. The game will only let me use the workbench in creative mode. Please respond to this report

**Comment by ghost** [comment]
It works for me. What version of the mod/minecraft/forge are you using?

**Comment by JamesX257** [comment]
Oh Nevermind, it started working a while ago, it was just a bug

**Comment by ghost** [comment]
> Oh Nevermind, it started working a while ago, it was just a bug

Ok cool you should close this ticket then
