### ISSUE TITLE
[1.16.5] Two-Handed Weapon models double rendering in 3rd person

### ISSUE THREAD

**Issue by BigMartin58** [MrCrayfish/MrCrayfishGunMod#194]
The Rifle, Assault Rifle, Heavy Rifle, and Shotgun are all double rendering while in 3rd person. First person works just fine. Also, the Bazooka, Minigun, and Pistol are fine. I don't know how to fix.
![2021-08-12_01 10 57](https://user-images.githubusercontent.com/88823811/129162066-307d7efb-378b-40cb-94c1-245bd2114ce7.png)
![2021-08-12_01 11 02](https://user-images.githubusercontent.com/88823811/129162068-104c341a-764c-47cb-81f8-5279921db012.png)
![2021-08-12_01 11 05](https://user-images.githubusercontent.com/88823811/129162069-3a463a74-b624-4c1f-8427-72ad844702c2.png)

**Comment by copygirl** [comment]
Can confirm. Also happens for other players in multiplayer.

**Comment by Flooo1308** [comment]
Do you have the CavesandCliffs backport mod installed? This mod is causing the problem in my modpack, when i remove it the bug is gone. Unfortunately i cannot find a way to fix it without removing the mod. Try it, if you have it installed.

**Comment by MrCrayfish** [comment]
Just an incompatibility with another mod. This issue should no longer exist in 1.18 and above.
