### ISSUE TITLE
Exception in Recipe Serializer

### ISSUE THREAD

**Issue by dshadowwolf** [MrCrayfish/MrCrayfishGunMod#195]
The `WorkbenchRecipeSerializer` code throws an exception of `"result"` is not found in a recipe. This code appears to be identical to what is in the Vehicle Mod, as its text is "Missing Vehicle entry" instead of something that actually makes sense for the code, such as "Missing Recipe Result".

Ran into this when someone asked for help after getting the above error when trying to add a recipe using CraftTweaker and its `IRecipeManager.addJSONRecipe()` syntax, where they had mistakenly used `"results"` instead of `"result"`. The bad exception text meant that figuring out the issue took actually going into the code to see how a recipe that, at a quick glance, matched the format was expected to have a `vehicle`.

**Comment by MrCrayfish** [comment]
Don't use CraftTweaker, just use a datapack to override the recipe. Also "result" should be "vehicle"

**Comment by MrCrayfish** [comment]
```json
{
  "type": "vehicle:workstation",
  "vehicle": "vehicle:mini_bus",
  "materials": [
    {
      "tag": "forge:ingots/iron",
      "count": 128
    },
    {
      "item": "minecraft:gray_wool",
      "count": 5
    },
    {
      "tag": "forge:glass_panes",
      "count": 9
    },
    {
      "item": "minecraft:redstone",
      "count": 12
    },
    {
      "item": "vehicle:panel",
      "count": 16
    }
  ]
}
```

**Comment by MrCrayfish** [comment]
Also wrong repository

**Comment by dshadowwolf** [comment]
The error came from "Crayfish Gun Mod" so no, not wrong repository. 

Check the file - it literally has `Missing Vehicle entry` for the exception and it will trigger even from a datapack if the `result` part is missing. (or if, like in this case, they specify `results` instead of `result`)

**Comment by MrCrayfish** [comment]
My bad, I'll get this fixed

**Comment by MrCrayfish** [comment]
Fixed in recent versions
