### ISSUE TITLE
Scoping whilst in third person causes the HUD to be transformed based on scope zoom.

### ISSUE THREAD

**Issue by NighthowlerStudios** [MrCrayfish/MrCrayfishGunMod#196]
Self explanatory.  Really wish you would add some better third person things.  for now I'm using shoulder surfing to help with crosshair, but it's also not scopable.

**Comment by MrCrayfish** [comment]
Not really self explanatory, I can't reproduce the issue. Create a new issue if this is still present on modern version (1.18.2+)

**Comment by NighthowlerStudios** [comment]
Issue only occurs in 1.16.5 1.0.X, the issue had since disappeared in latest 1.2.X.  no further investigation required.  no clue how you fixed it without knowing haha
