### ISSUE TITLE
unable to reload using assault rifle at 1.12.2

### ISSUE THREAD

**Issue by JunEvergreen** [MrCrayfish/MrCrayfishGunMod#202]
Hello, as I tried to test the guns in creative mode whenever I use assault rifle in the inventory I wont be able to reload anymore, same as most of the guns wont be able to reload using the default "R" key, did I do something wrong?

**Comment by 16-squared** [comment]
Did you remember to unload them first? Firing in creative mode does not deplete the magazines.
