### ISSUE TITLE
Weapons animation bug

### ISSUE THREAD

**Issue by Elmonocucuy** [MrCrayfish/MrCrayfishGunMod#203]
Good morning or evening

As we can witness in the following image when I put the third person can witness a very nice animation bug, being more precise the weapon visually doubles being a static image, on the other hand when we enter the weapon to the other hand is bugged giving a perspective of the weapon itself in image format; I witnessed this bug recently by adding a mod called CavesAndCliffsBackport, testing to see what is the mod or other factor qeu affect this I think it is that mod. If any moderator or person in charge of this bug can help me I would be very grateful.

![image](https://user-images.githubusercontent.com/86699970/133816023-b5f9a162-d5f5-4c40-93f1-73fae2878ac2.png)
![image](https://user-images.githubusercontent.com/86699970/133816102-92542295-2edd-47d3-8f62-bd7acae92e48.png)
![image](https://user-images.githubusercontent.com/86699970/133816151-7a64c1ba-df1b-4a7d-8650-caa08fd68639.png)

**Comment by MrCrayfish** [comment]
Unlikely to fix, their mod is closed source (for obvious reasons). I would suggest just using 1.18+
