### ISSUE TITLE
Workbench display not working

### ISSUE THREAD

**Issue by celakk1** [MrCrayfish/MrCrayfishGunMod#205]
when i was making weapons in workbench theres no display or something to see what im making can someone help me?
![2021-09-27_22 19 03](https://user-images.githubusercontent.com/49827604/134979276-0b83ddf3-ffd5-4424-a717-2852893a34d9.png)

**Comment by Ch1216** [comment]
Do you have optifine?

**Comment by MrCrayfish** [comment]
Can't reproduce, likely Optifine or another mod.

**Comment by MrCrayfish** [comment]
Open a new issue if still present on modern versions (1.18.2 and above)
