### ISSUE TITLE
All players on server hear reload sound effect

### ISSUE THREAD

**Issue by ghost** [MrCrayfish/MrCrayfishGunMod#208]
**Description:**
When a player reloads on a forge dedicated server all other online players hear the reload. This was tested with the heavy rifle.

**Verions:**
Minecraft 1.16.5
Forge 1.16.5-36.2.6
Java 8-301-64 bit
crayfish-gun-mod-1.0.1-1.16.3
obfuscate-0.6.2-1.16.3

**Comment by MrCrayfish** [comment]
Thnaks for report. Fixed in https://github.com/MrCrayfish/MrCrayfishGunMod/commit/8d7cbe771813efd05f7d0e27c03b1db05ced479c
