### ISSUE TITLE
Attachments not working

### ISSUE THREAD

**Issue by JuanJoseAriasJaramillo** [MrCrayfish/MrCrayfishGunMod#213]
1.16.5 
mod version; 
cgm-1.0.1-1.16.3.jar
am trying to put together guns and attachments and is not working, maybe am doing wrong; 
![image](https://user-images.githubusercontent.com/67617032/143150065-f2c8738c-4d81-45e6-a322-b7a74e468e53.png)

**Comment by MrCrayfish** [comment]
It doesn't work like that in the new version. Press Z while holding the weapon.
