### ISSUE TITLE
Tengo problemas

### ISSUE THREAD

**Issue by TatsuyaLucifer** [MrCrayfish/MrCrayfishGunMod#214]
Instale el mod de las armas y pongo el mod en la carpeta mods, cuando incio toda carga bien me dice que el mod esta activo pero al entrar a mi mundo o un mundo nuevo no encuentro la mesa para crear las armas mucho menos las armas a pesar de que busco como se debe incluso miro en la mesa de crafteo pero no me sale nada, hay algo que pueda hacer para que funcione? nose si es problema del forge o que asi que ayudenme por favor

**Comment by MrCrayfish** [comment]
You need to use the Workbench, not the crafting table to craft weapons. Also please use english.

**Comment by TatsuyaLucifer** [comment]
> Necesitas usar el banco de trabajo, no la mesa de trabajo para fabricar armas. También utilice inglés.

Sorry for having used Spanish and with respect to what you tell me, I did not use the crafting table to create the weapons but to create the Work bench because it does not appear to me anywhere, that is, it is as if I were playing normal minecraft, And the work bench does not appear even in creative and I want to know how I can solve that error if I need a specific Forge or what can I do?

**Comment by TatsuyaLucifer** [comment]
Sorry for having used Spanish and with respect to what you tell me, I did not use the crafting table to create the weapons but to create the Work bench because it does not appear to me anywhere, that is, it is as if I were playing normal minecraft, And the work bench does not appear even in creative and I want to know how I can solve that error if I need a specific Forge or what can I do?
