### ISSUE TITLE
minecraft 1.18 gun mod Crash on start

### ISSUE THREAD

**Issue by TheRTGGaming** [MrCrayfish/MrCrayfishGunMod#218]
[debug.log](https://github.com/MrCrayfish/MrCrayfishGunMod/files/7678215/debug.log)

The log file when I was loading Minecraft. Only crashes when I have the gun mod installed.

**Comment by ghost** [comment]
I have this problem too I just wanted to play with the mod because I was at school today and this was a cool surprise

**Comment by Ch1216** [comment]
This issues is fixed now
