### ISSUE TITLE
[BUG?] Astral Sorcery's Resplendent Prism

### ISSUE THREAD

**Issue by LunarFactory** [MrCrayfish/MrCrayfishGunMod#221]
Idk why it happens, but with Astral Sorcery, CGM's Enchantments don't appear in Resplendent Prism and it doesn't give level plus to gun's enchantment.

* Resplendent Prism is a curio that plus 1 or 2 levels into specific/existing/all enchantment.

**Comment by MrCrayfish** [comment]
I'm not sure since I don't develop that mod. I believe I am registering all my enchantments as normal, no random hacks that would prevent other mods from seeing them.
