### ISSUE TITLE
Suggestion: make bullets use copper instead of iron

### ISSUE THREAD

**Issue by ghost** [MrCrayfish/MrCrayfishGunMod#222]
So I think it would be great if you changed the recipe for basic bullet, advacned bullet, and shell to use copper instead of iron. I think it would make copper a lot more useful (since its a vanilla ore in 1.18 now!) it would also be more realistic! If you don't really like the idea maybe make it a config option at least? Thanks for considering!
![bullets are copper](https://user-images.githubusercontent.com/82549089/145740957-4d50c4ad-ed22-4641-83e1-b5e876cffa70.PNG)
![current recipe](https://user-images.githubusercontent.com/82549089/145740969-b2ee92c4-8a39-4e5b-8bdc-3be3e7a357b1.PNG)
![copper nugg](https://user-images.githubusercontent.com/82549089/145740971-fe19f96b-c7a0-47bf-a7d1-17a1c6aa849a.PNG)

**Comment by NighthowlerStudios** [comment]
You can do this yourself by editing the recipes in the datapack

**Comment by ghost** [comment]
> You can do this yourself by editing the recipes in the datapack

Thanks! Although I would prefer if it was just part of the mod or a config option

**Comment by ghost** [comment]
I just realized there is no vanilla copper nuggets, only ingots. So I thought about this:

- 1 copper ingot and 2 gunpowder makes 64 basic bullets
- 1 copper ingot and 2 gunpowder makes 32 advanced bullets
- 1 copper ingot and 2 gold nuggets and 2 gunpowder makes 48 shells

**Comment by MrCrayfish** [comment]
Yes, I will consider this change.

**Comment by ghost** [comment]
[GunModCopperBullets.zip](https://github.com/MrCrayfish/MrCrayfishGunMod/files/8125979/GunModCopperBullets.zip)

here is a datapack I made to accomplish this, I still think it should be added to the mod by default or maybe as a config option
