### ISSUE TITLE
Unable to Reload + Ticking Player Crash

### ISSUE THREAD

**Issue by soup587** [MrCrayfish/MrCrayfishGunMod#226]
Both issues appear to be related based on what I've seen elsewhere, but often I'm unable to reload when starting up a world. If I close said world, restart my game, then re-open the world, I get an immediate tickingplayer crash relating to a "synced data key cgm:aiming" not being registered.
[crash-2021-12-17_18.55.11-server.txt](https://github.com/MrCrayfish/MrCrayfishGunMod/files/7737254/crash-2021-12-17_18.55.11-server.txt)
 
 
 Edit: The corruption only seems to occur if the game is saved and restarted while I'm holding a CGM weapon
 Edit 2: It might be random? Or only if it's in my hotbar? OR if I change my keybinds???

**Comment by twu425** [comment]
I'm getting the same error

**Comment by MrCrayfish** [comment]
Send your logs and the steps that happened before the crash

**Comment by twu425** [comment]
I got nearly the exact same error log and I got the error when loading up a world. Looking from the log, I made I blind guess that it could be my keybinds. After removing the keybind conflicts with this mod and another one the error didn't seem to happen again. It could just be a coincidence though.

**Comment by MrCrayfish** [comment]
Again, send your game logs and crashes.

**Comment by twu425** [comment]
[crash-2021-12-19_19.13.59-client.txt](https://github.com/MrCrayfish/MrCrayfishGunMod/files/7742367/crash-2021-12-19_19.13.59-client.txt)

**Comment by twu425** [comment]
[crash-2021-12-19_19.13.50-server.txt](https://github.com/MrCrayfish/MrCrayfishGunMod/files/7742369/crash-2021-12-19_19.13.50-server.txt)

**Comment by MrCrayfish** [comment]
Are you able to also send your regular logs? The ones that match the crash logs.

**Comment by twu425** [comment]
[2021-12-19-4.log](https://github.com/MrCrayfish/MrCrayfishGunMod/files/7746872/2021-12-19-4.log)

**Comment by MrCrayfish** [comment]
Thanks. I've looked through the logs you've sent, and it seems this is going to be a difficult issue to solve. The log is clearly stating that the keys are registered
```
[19:10:50] [modloading-worker-0/INFO]: Registered synced data key cgm:aiming for minecraft:player
[19:10:50] [modloading-worker-0/INFO]: Registered synced data key cgm:shooting for minecraft:player
[19:10:50] [modloading-worker-0/INFO]: Registered synced data key cgm:reloading for minecraft:player
```
but then the crash says
```
java.lang.IllegalArgumentException: The synced data key cgm:aiming for minecraft:player is not registered!
```

I do have a question, does this happen if the only mod installed is the Gun Mod (and Framework obviously)? The biggest problem I have is not being able to replicate the issue. I can reload worlds, rejoin servers, etc and have no crash. Usually bugs like this occur only when certain mods are install with the Gun Mod. It's possible that another mod has modified something.
Would you be willing to test a custom version of the mod that includes additional logging?

**Comment by twu425** [comment]
Sure.

**Comment by Zapatocuantico** [comment]
i have the same problem

**Comment by MrCrayfish** [comment]
So the issue actually lies within the underlying library (Framework). Here is a custom version that has extra logging. The JAR file is inside the zip so make sure you extract it first. Put this on your client and server and if the issue happens again, send logs for both client and server (like @twu425 did)
[framework-0.2.3-1.18.1.zip](https://github.com/MrCrayfish/MrCrayfishGunMod/files/7797459/framework-0.2.3-1.18.1.zip)

**Comment by MrCrayfish** [comment]
Any follow up to this with the custom version of Framework?

**Comment by MrCrayfish** [comment]
Issue should now be resolved. Please use the latest version of Framework and Gun Mod
