### ISSUE TITLE
Issue: Over Capacity bug | 1.18.1

### ISSUE THREAD

**Issue by jekser2** [MrCrayfish/MrCrayfishGunMod#233]
After enchanting a gun using an anvil with overcapacity and realoding it to have full magazine, the weapon will be at a state of higher ammo capacity but when the item enchantment is remove with a grindstone or command (only had been tested on grindstone) the item will have a bug durability. 

weapon that are effected seems to be weapon that have more than 1+ bullets

![image](https://user-images.githubusercontent.com/79689194/147475046-ffc01c89-4da3-460a-8870-9cf55d571f87.png)

**Comment by MrCrayfish** [comment]
This seems to have been fixed.
