### ISSUE TITLE
Can't launch the game with the mod enabled.

### ISSUE THREAD

**Issue by Ugapiku** [MrCrayfish/MrCrayfishGunMod#238]
Giving you crash report when launching the mod through CurseForge. 
[crash-2022-01-07_02.02.09-client.txt](https://github.com/MrCrayfish/MrCrayfishGunMod/files/7825401/crash-2022-01-07_02.02.09-client.txt)

**Comment by MrCrayfish** [comment]
You're using an old version of Framework
