### ISSUE TITLE
Crash report - Maps are crashing after a while. total loss of maps 

### ISSUE THREAD

**Issue by allanisPixel** [MrCrayfish/MrCrayfishGunMod#243]
Hello MrCrayfish! I really like the work you do but unfortunately I come here to report a chash (which is probably incompatibility between mods) The crash usually occurs on "serious" maps where I create some more elaborate construction and use more objects from the mods on the map (nothing reactive, or machines just decorative blocks, fancy from bibliocraft). After 2 or 3 days of work the map will refuse to open and load the world resulting in a crash and the game crashing. As your mod is mentioned in the error log I am sending this to you and the other devs mentioned in the error log. 

Minecraft version: 1.12.2
Forge:1.12.2 - 14.23.5.28.59
Obfuscate: obfuscate-0.4.2-1.12.2
MrCrayfishGunMod: guns-0.15.3-1.12.2

Mods:
-TL skin and cape
-archaicguns-0.4.0
-Baubles-1.12-1.5.2
-BiblioCraft[v2.4.5][MC1.12.2]
-Bloodmoon-MC1.12.2-1.5.3
-Bookshelf-1.12.2-2.3.590
-coffeework-1.2.9
-CookingForBlockheads_1.12.2-6.5.0
-crimsonrevelations-0.8
-DimensionalDoors-1.12.2-3.1.2-UNOFFICIAL
-ElectroblobsWizardry-4.3.4-MC1.12.2
-foamfix-0.10.14-1.12.2
-forbidden_arcanus-1.12.2-1.1.4
-geckolib-forge-1.12.2-3.0.16
-growthcraft-1.12.2-4.2.2.1
-guns-0.15.3-1.12.2(MrCrayfish's Gun Mod)
-HammerLib-1.12.2-2.0.6.31
-horsestandstill-1.12.2-1.0.0(Stupid Horse Stand Still)
-Hwyla-1.8.26-B41_1.12.2
-iceandfire-1.9.1-1.12.2
-ImprovableSkills-1.12.2-12.4.67
-ImprovedMobs-1.12.2-1.6.10
-jei_1.12.2-4.16.1.302 
-JJ+Races+1.12-1.12.2-v1.0.14
-journeymap-1.12.2-5.7.1
-levelhearts-1.12.2-2.4.0
-llibrary-1.7.20-1.12.2
-LootBags-1.12.2-2.5.8.5
-Mantle-1.12-1.3.3.55
-MusicCraft-3.2.3
-obfuscate-0.4.2-1.12.2
-OptiFine-1.12.2_HD_U_G5
-ordinarycoins-1.12.2-1.5
-Pam's+BreadCraft+1.12.2-1.1.2
-Pam's+HarvestCraft+1.12.2zg
-Patchouli-1.0-23.6
-PizzaCraft-1.12.2-2.0.19
-TConstruct-1.12.2-2.13.0.183
-TenshiLib-1.12.2-1.2.4
-Thaumcraft_1.12.2_6.1.BETA26
-ThaumicAugmentation-1.12.2-2.1.5
-ThaumicJEI-1.12.2-1.6.0-27
-tinkersjei-1.2
-tlskincape1.12.2-1.4
-TravelersBackpack-1.12.2-1.0.35
-twilightforest-1.12.2-3.11.1021-universal
-Voice+Chat+Reloaded-1.2.5
-Wawla-1.12.2-2.6.275
-WizardryFates-2.1.0

Log crash:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  TenshiCore (TenshiLib-1.12.2-1.2.4.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
  HCASM (HammerLib-1.12.2-2.0.6.31.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.5.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 1/20/22 6:10 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/entity/Entity$2
	at net.minecraft.entity.Entity.func_85029_a(Entity.java:2675)
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1877)
	at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:221)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186053_a(AnvilChunkLoader.java:602)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186050_a(AnvilChunkLoader.java:529)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_72838_d(World.java:1211)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:377)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:166)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1813388144 bytes (1729 MB) / 2885681152 bytes (2752 MB) up to 3154116608 bytes (3008 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: ~~ERROR~~ NoClassDefFoundError: net/minecraftforge/common/util/TextTable$1
	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TenshiCore (TenshiLib-1.12.2-1.2.4.jar)
  com.flemmli97.tenshilib.asm.ASMTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
HCASM (HammerLib-1.12.2-2.0.6.31.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.5.jar)
  thecodex6824.thaumicaugmentation.core.TATransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	HammerCore Debug Information: 
		Dependent Mods:
			-Improvable Skills (improvableskills) @ 12.4.67

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Patchouli open book context: n/a
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Lyriam2'/299, l='Esse é o mundo :3', x=518.30, y=63.00, z=245.34]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 30.0.100.9864
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by MrCrayfish** [comment]
Unfortuantely unable to help. The stacktrace doesn't contain anything related to my mod, also 1.12.2 is discontinued now.
