### ISSUE TITLE
1.18 forge 39.0.55 issue

### ISSUE THREAD

**Issue by amandexspeed** [MrCrayfish/MrCrayfishGunMod#245]
When i tried to use workbenck the game crashed and this happened
![imagem_2022-01-23_133749](https://user-images.githubusercontent.com/60000299/150688463-d2ad7107-0452-44a3-89e3-286b2294b25d.png)
[crash-2022-01-23_12.56.38-server.txt](https://github.com/MrCrayfish/MrCrayfishGunMod/files/7920878/crash-2022-01-23_12.56.38-server.txt)

**Comment by Strana** [comment]
#242 Related issue

**Comment by MrCrayfish** [comment]
Updated to latest versions for fix.
