### ISSUE TITLE
My server crashes on version 1.0 of 1.15.2

### ISSUE THREAD

**Issue by VolvelaBVolvic** [MrCrayfish/MrCrayfishGunMod#246]
My server works with version 0.16.1 and 0.16 but with 1.0 the server crashes so I send you the crash report if you could help me please

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 1/23/22 8:36 PM
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	MrCrayfish's Gun Mod (cgm) encountered an error during the common_setup event phase
§7Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:156) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:46) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 5.4.0-74-generic
	Java Version: 1.8.0_292, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1216418448 bytes (1160 MB) / 1981284352 bytes (1889 MB) up to 2143813632 bytes (2044 MB)
	CPUs: 3
	JVM Flags: 3 total; -XX:MaxMetaspaceSize=200M -Xmx2300M -Xms1150M
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-2.2.1-service.jar eventbus PLUGINSERVICE 
		/forge.jar object_holder_definalize PLUGINSERVICE 
		/forge.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge.jar capability_inject_definalize PLUGINSERVICE 
		/forge.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.57
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.57-server.jar Minecraft {minecraft@1.15.2 SIDED_SETUP}
		voicechat-1.15.2-1.0.2.jar Simple Voice Chat {voicechat@1.15.2-1.0.2 SIDED_SETUP}
		smartphone-1.15.2-1.2.0.jar Smartphone {smartphone@1.15.2-1.2.0 SIDED_SETUP}
		IamMusicPlayer-1.15.2-1.2.jar Iam Music Player {iammusicplayer@1.2 SIDED_SETUP}
		economyinc-1.6.9.4.jar Economy Inc. {economyinc@1.6.8 SIDED_SETUP}
		simpleworldtimer-1.15.2-1.1.2-beta.jar Simple World Timer {simpleworldtimer@1.15.2-1.1.2-beta SIDED_SETUP}
		cgm-1.0-1.15.2.jar MrCrayfish's Gun Mod {cgm@1.0.0 ERROR}
		coffee-mod_1.15.2-1.1.1.jar Coffee mod {coffeemod@1.1.1 SIDED_SETUP}
		TrackAPI-1.15.2-forge-1.2.1.jar TrackAPI {trackapi@1.2 SIDED_SETUP}
		camera-1.6.11.jar Camera Mod {camera@1.6.11 SIDED_SETUP}
		Decoration and furniture mod.jar Decoration and furniture mod {decoration_mod@1.0.0 SIDED_SETUP}
		CookingForBlockheads_1.15.2-8.0.3.jar Cooking for Blockheads {cookingforblockheads@8.0.3 SIDED_SETUP}
		[1.15.2] SecurityCraft v1.8.23.2.jar SecurityCraft {securitycraft@v1.8.23.2 SIDED_SETUP}
		[1.15.2] Valtiel s Clothes Mod-2.3.1.jar Valtiel s Clothes Mod {vclothes@2.3.1 SIDED_SETUP}
		obfuscate-0.5.0-1.15.2.jar Obfuscate {obfuscate@0.5.0 SIDED_SETUP}
		vehicle-mod-0.44.1-1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.44.1 SIDED_SETUP}
		betteranimalsplus-1.15.2-10.2.0.jar Better Animals Plus {betteranimalsplus@10.2.0 SIDED_SETUP}
		worldedit-forge-mc1.15.2-7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c SIDED_SETUP}
		u_team_core-1.15.2-3.0.0.159-SNAPSHOT.jar U Team Core {uteamcore@3.0.0.159-SNAPSHOT SIDED_SETUP}
		mcw-doors-1.0.3-mc1.15.2.jar Macaw's Doors {mcwdoors@1.0.3 SIDED_SETUP}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 SIDED_SETUP}
		ImmersiveRailroading-1.15.2-forge-1.9.1.jar Immersive Railroading {immersiverailroading@1.15.2-forge-1.9.1 SIDED_SETUP}
		sworddisplay-1.15.2-1.5.1.jar Sword Displays {sworddisplay@1.15.2-1.5.1 SIDED_SETUP}
		Reeves'sFurnitureMod-3.1.1-1.15.2.jar Reeves's Furniture Mod {reevess_furniture_mod@3.1.1 SIDED_SETUP}
		NiftyBlocks-1.22.jar NiftyBlocks {nifty@1.22 SIDED_SETUP}
		NefsMedievalPub+v0.9(1.15.2).jar Nef Deco Mod {nefdecomod@0.9 SIDED_SETUP}
		XL-Food-Mod-1.15.2-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 SIDED_SETUP}
		forge-1.15.2-31.2.57-universal.jar Forge {forge@31.2.57 SIDED_SETUP}
		dipomoneymod-1.2.1.jar Dipo's Money Mod {dipomoneymod@1.2.1 SIDED_SETUP}
		PlayingCards-1.0.3-MC1.15.2.jar Playing Cards {playingcards@1.15.2-1.0.3 SIDED_SETUP}
		supplementaries-1.15.2-0.9.27 .jar Supplementaries {supplementaries@1.15.2-0.9.27 SIDED_SETUP}
		Hospital Mod 1.15.2 (31.1.43).jar The Hospital Mod {the_hospital_mod@1.0.0 SIDED_SETUP}
		UniversalModCore-1.15.2-forge-1.1.3.jar Universal Mod Core {universalmodcore@1.1.3 SIDED_SETUP}
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by MrCrayfish** [comment]
1.15.2 is discontinued
