### ISSUE TITLE
Third person view bug when holding a gun in 1.12.2

### ISSUE THREAD

**Issue by AAli107** [MrCrayfish/MrCrayfishGunMod#248]
When I play multiplayer or when I see myself holding the gun in the third person view, the gun I carry gets duplicated and the player has no custom gun holding animation animations.

I tried reinstalling the mod still, nothing changed.
I'm on 1.12.2 btw.

Any help would be appreciated.

![2022-01-26_12 44 58](https://user-images.githubusercontent.com/22107799/151140783-521ecb70-be0e-46b1-adf0-39725841f822.png)

**Comment by TanTanMc** [comment]
try to change version

**Comment by MrCrayfish** [comment]
Just a mod incompatibility. Update to a modern version (1.18.2 or above) since 1.12.2 is now discontinued.

**Comment by AAli107** [comment]
Aww man... :(
