### ISSUE TITLE
Unable to reload on server

### ISSUE THREAD

**Issue by ArIGn** [MrCrayfish/MrCrayfishGunMod#249]
I cant seem to reload on cgm 1.1.3 on my server. I tried testing in single player and it works fine. I have tried to restart my server and it does not fix it. Is there any fix for this?

**Comment by MrCrayfish** [comment]
I have a fix coming soon, it's for Framework.

**Comment by MrCrayfish** [comment]
I will though publish I new update for the Gun Mod that will just make it require the newer version of Framework.
