### ISSUE TITLE
CLIENTSIDE NPE CRASH

### ISSUE THREAD

**Issue by kreezxil** [MrCrayfish/MrCrayfishGunMod#25]
NPE, not sure what caused it the player didn't say, client side crash, appears to be one-off

https://paste.dimdev.org/emenifiqok.mccrash

**Comment by MrCrayfish** [comment]
Thanks for the report. I will have a patch soon!

**Comment by kreezxil** [comment]
does version 0.12.2 fix this issue?

**Comment by MrCrayfish** [comment]
Yes

**Comment by kreezxil** [comment]
thanks.
