### ISSUE TITLE
Game Crashes every now and then when joining a world.

### ISSUE THREAD

**Issue by IvorAmlug** [MrCrayfish/MrCrayfishGunMod#254]
"The game crashed whilst ticking player
Error: java.lang.IllegalArgumentException: The synced data key cgm:aiming for minecraft:player is not registered!
Exit-Code: -1"
Full Crash Log here:
https://pastebin.com/HFM2f4yA

**Comment by CDAGaming** [comment]
Have had this issue too, where it is unable to sync cgm:aiming for some reason.

**Comment by benpaq** [comment]
same here, making a new world is often fine, but loading a saved world is where i crash.. but it worked on my server?

**Comment by MrCrayfish** [comment]
Are you using the latest version of Framework?

**Comment by MrCrayfish** [comment]
Duplicate of https://github.com/MrCrayfish/MrCrayfishGunMod/issues/241

**Comment by MrCrayfish** [comment]
Just to summerize, this has been an issue for a while now. I've been struggling to create a fix since it's not as simple as it seems.
