### ISSUE TITLE
Cant reload on server but can on single player

### ISSUE THREAD

**Issue by ArIGn** [MrCrayfish/MrCrayfishGunMod#256]
I have both gun mod 1.1.3 and framework 0.2.3 installed but I still cant reload in my server. It works fine in single player but not in multiplayer. Is there a reset I can do for framework or cgm?

**Comment by robotalian234** [comment]
What's your Forge version?

**Comment by ArIGn** [comment]
> What's your Forge version?

Server - Forge 1.18.1 (39.1.2)
Client - Forge 1.18.1 (39.0.79)

**Comment by robotalian234** [comment]
So then like I had in my post, I have the same Forge and Minecraft version as you and have the issue. So far it seems like it's an updated Forge issue. Before I updated I had 39.0.70 something and the reload worked, then I updated to the newest Forge and it doesn't.

**Comment by MrCrayfish** [comment]
Update to the latest verison. I have now solved the issue.
