### ISSUE TITLE
1.18.1 Cant reload gun

### ISSUE THREAD

**Issue by ghost** [MrCrayfish/MrCrayfishGunMod#257]
I played my modpack an hour before but now i cant reload my gun i changed some keybinds and nothing has worked.

[I tried some other things and it has not worked]

Minecraft : 1.18.1

Mod : gun-mod-1.1.3-1.18.1.jar

**Comment by ghost** [comment]
(No mod should interfere with it as it worked before)

**Comment by robotalian234** [comment]
What is your Forge version?

**Comment by ghost** [comment]
> What is your Forge version?

Forge - 39.0.88

**Comment by robotalian234** [comment]
This is what Mr. Crayfish said on my post for the not reloading issue;

"It's not Forge, just tested on 39.1.2 and it reloads fine. It's a bug that been plaguing the mod for a long time and no clear indication of the cause. Just simply the fact that it's seems to be random that a player can't reload makes the problem difficult to solve, let alone reproduce."

**Comment by MrCrayfish** [comment]
Update to the latest verison. I have now solved the issue.
