### ISSUE TITLE
Arms do not sway in first person

### ISSUE THREAD

**Issue by minatoast** [MrCrayfish/MrCrayfishGunMod#259]
This one is a hard one to catch, but I noticed when after opening my inventory when running. Although it's obviously not a huge deal because you can't see it outside of FP perspective, but it is a bug nonetheless.

I'm guessing the modeling with holding guns interferes with it somehow.

I wanted to use this mod with the First Person Model mod but it looks ridiculous without my arms moving lol.

**Comment by MrCrayfish** [comment]
Mods are just not compatible, simple as that.

**Comment by minatoast** [comment]
Well, this is the case with no other mod installed, and I don't think it's supposed to be like that. I just used the First Person Mod as an example of why it could be an issue.
