### ISSUE TITLE
Unable To Reload

### ISSUE THREAD

**Issue by robotalian234** [MrCrayfish/MrCrayfishGunMod#261]
Forge Version - 39.1.2
Minecraft Version - 1.18.1

I believe since updating from Forge version 39.0.70 something to the newest Forge version has broken the reload of the weapons. I'm now unable to reload the weapons. I do have 73 mods, but none of those have affected the mod until updating and now I can't reload. Might be the possible reason people are having the issues as well if that could get looked into.

**Comment by kenzih95** [comment]
Yea same here, I tried exit then log back in many time, sometime it will be able to reload, "sometime".

**Comment by robotalian234** [comment]
So then I believe we can narrow it down to the updated Forge breaking the mod. For now we'll have to wait for the mod to update to the newest Forge version.

**Comment by MrCrayfish** [comment]
It's not Forge, just tested on 39.1.2 and it reloads fine. It's a bug that been plaguing the mod for a long time and no clear indication of the cause. Just simply the fact that it's seems to be random that a player can't reload makes the problem difficult to solve, let alone reproduce.

**Comment by RKnevels** [comment]
OK so my game gave me this. (Its on Brazilian Portuguese - GAME STOPED WORKING)
![gunmod err](https://user-images.githubusercontent.com/102393035/160213875-bb3b7f5f-d743-4e4b-990f-79cc1ae8a4aa.png)
After playing for some hours, closed minecraft, gone lunchiing. When returned, on first launch, the error apeared.
After that. no reload could be done on any weapons.
Here is the complete log.
[crash-2022-03-25_12.08.54-client.txt](https://github.com/MrCrayfish/MrCrayfishGunMod/files/8354246/crash-2022-03-25_12.08.54-client.txt)
I manage to fix it everytime, deleting some folders from minecraft folder. Don't know exacly which results in solvind it.
![folders](https://user-images.githubusercontent.com/102393035/160214114-a4d6e20f-638c-4c22-a49d-11c676385d22.png)
and remove the config files from config forlder and serverconfig (cgm*.toml)

**Comment by MrCrayfish** [comment]
Update to the latest verison. I have now solved the issue.
