### ISSUE TITLE
Minecraft 1.18.1 cannot enter the game

### ISSUE THREAD

**Issue by xzl0326** [MrCrayfish/MrCrayfishGunMod#265]
I used Gun Mod 1.1.3 which caused the game to flash back and cannot enter. The following is the error log
[minecraft-exported-crash-info-2022-03-08T15-54-11.zip](https://github.com/MrCrayfish/MrCrayfishGunMod/files/8204199/minecraft-exported-crash-info-2022-03-08T15-54-11.zip)

**Comment by MrCrayfish** [comment]
Install Framework (https://www.curseforge.com/minecraft/mc-mods/framework)
