### ISSUE TITLE
Unwanted Infinite Ammo on 1.16.5 server. 

### ISSUE THREAD

**Issue by DrewTheDev** [MrCrayfish/MrCrayfishGunMod#268]
While playing on a Pebblehost server, all guns have infinite ammunition. Even ones crafted in survival through a gun bench. The addon mod "Mo'Guns" is also installed. Spawning in the gun on the server with no bullets it does not shoot, but once it has a single bullet loaded it will continue it's usual infinite ammo activity.

Mod version: cgm-1.1.0-1.16.5
Forge version: 36.2.29

**Comment by MrMilkdud** [comment]
Mo guns is the problem.

**Comment by MrCrayfish** [comment]
Since this is an issue with an addon, not the base mod, I'll be closing the issue.
