### ISSUE TITLE
1.2.0/1.2.1 for 1.16.5 - Mod loading error on client startup

### ISSUE THREAD

**Issue by zaeonNineZero** [MrCrayfish/MrCrayfishGunMod#278]
Mod throws an UnableToFindField exception when loading.  Tested on Forge versions 36.2.28 and 36.2.33.

"Caused by 0: net.minecraftforge.fml.common.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: instanceToChannel"

Crash logs for both tested Forge versions are included.
[crash-2022-04-08_14.30.17-fml.txt](https://github.com/MrCrayfish/MrCrayfishGunMod/files/8454517/crash-2022-04-08_14.30.17-fml.txt)
[crash-2022-04-08_14.39.26-fml.txt](https://github.com/MrCrayfish/MrCrayfishGunMod/files/8454518/crash-2022-04-08_14.39.26-fml.txt)

**Comment by JetpackRescue** [comment]
i'm also having this error

**Comment by flin7101** [comment]
Same Issue Error.

**Comment by zaeonNineZero** [comment]
Issue appears to be fixed in version 1.2.3.
