### ISSUE TITLE
Game crashes when trying to reload a gun with no ammo in your inventory

### ISSUE THREAD

**Issue by Chancho91** [MrCrayfish/MrCrayfishGunMod#283]
Here is thee crash report. 
[crash-2022-04-13_12.10.51-server.txt](https://github.com/MrCrayfish/MrCrayfishGunMod/files/8483047/crash-2022-04-13_12.10.51-server.txt)

**Comment by MrCrayfish** [comment]
Updated Backpacked to the latest version
