### ISSUE TITLE
Shooting gun does not respect ClickInputEvent

### ISSUE THREAD

**Issue by CreativeMD** [MrCrayfish/MrCrayfishGunMod#285]
Hey there,
I'm the author of PlayerRevive. Recently somebody reported this issue to me: https://github.com/CreativeMD/PlayerRevive/issues/84 
A player is able to shoot the gun even though all interactions should be disabled. I use the `ClickInputEvent`: [source](https://github.com/CreativeMD/PlayerRevive/blob/1.18/src/main/java/team/creative/playerrevive/client/ReviveEventClient.java#L67).
Not sure how this event is bypassed. I can't fix it from my end, maybe fire the event yourself. Normally it's fired in `Minecraft.continueAttack(boolean)`.

In Regards
CreativeMD

**Comment by CreativeMD** [comment]
I had to switch to a different event called `InteractionKeyMappingTriggered`, not sure if this causes this incompatibility to reappear.

**Comment by MrCrayfish** [comment]
I've recently switched to ClickInputEvent and manually added compat https://github.com/MrCrayfish/MrCrayfishGunMod/commit/2a091ded10adf311273a816ddf2dfc111e01ccd8
