### ISSUE TITLE
Unable to reload ammo from Backpacked

### ISSUE THREAD

**Issue by Dr-WeiAL** [MrCrayfish/MrCrayfishGunMod#287]
If there is ammo in the inventory, it can be reloaded with the ammo in the Backpacked, but if there is no ammo in the inventory it cannot be reloaded from the Backpacked

![image](https://user-images.githubusercontent.com/47446553/164518860-c6b726ab-aae7-462d-8d0d-2145cf758d4b.png)
![image](https://user-images.githubusercontent.com/47446553/164518887-088b6545-415f-411a-9106-90156e2a9dba.png)
That way you can reload the ammo

![image](https://user-images.githubusercontent.com/47446553/164518966-f5731196-2e09-4efa-af03-16f52d321a03.png)
This way you can't reload the ammo

**Comment by MrCrayfish** [comment]
Do you have the Marksman enchantment applied to the backpack?

**Comment by Dr-WeiAL** [comment]
> Do you have the Marksman enchantment applied to the backpack?

The backpack has this enchantment, and the bow can normally use the arrows in the backpack

**Comment by MrCrayfish** [comment]
Which Minecraft version and are you using the latest versions of both mods?

**Comment by Dr-WeiAL** [comment]
> Which Minecraft version and are you using the latest versions of both mods?

All are the latest version of 1.18.2
