### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Chancho91** [MrCrayfish/MrCrayfishGunMod#288]
When I try to use the newest version of CGM and backpacker, the game crashes and gives me an error. 
[crash-2022-04-30_09.03.16-client.txt](https://github.com/MrCrayfish/MrCrayfishGunMod/files/8596944/crash-2022-04-30_09.03.16-client.txt)

**Comment by MrCrayfish** [comment]
Don't install Backpacker, it's not compatible with the newer versions of Backpacked. (As stated on the CurseForge page https://www.curseforge.com/minecraft/mc-mods/backpacker). Backpacker is going to be reworked to fit into the new Backpacked update i nthe future, not ETA.
