### ISSUE TITLE
New Compatibility Issue with Scoped Heavy Rifle

### ISSUE THREAD

**Issue by Darmandir** [MrCrayfish/MrCrayfishGunMod#291]
Hello, I've recently come across a new bug while playing; scoping in and headshotting an entity using a heavy rifle from a long distance causes the bullet to become a ticking entity, causing a crash. I do have a bit of an extensive modlist, and I'm not entirely sure where this issue stems from. I'll  keep testing when I have the time to try and figure out what could be causing the conflict.

[crash-2022-05-04_10.56.45-server.txt](https://github.com/MrCrayfish/MrCrayfishGunMod/files/8622098/crash-2022-05-04_10.56.45-server.txt)

**Comment by MrCrayfish** [comment]
Update Advanced Netherite since this is fixed.
