### ISSUE TITLE
Guns not draining ammo on survival server

### ISSUE THREAD

**Issue by sell488** [MrCrayfish/MrCrayfishGunMod#302]
I own a survival server with the mod installed, and the guns work mostly as they should. However, whenever anyone on the server shoots, ammo isn't drained from the gun. Digging through the console logs reveals that this exception is occurring.

11.06 18:32:42 [Server] Server thread/FATAL [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
11.06 18:32:42 [Server] Server thread/ERROR [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
11.06 18:32:42 [Server] INFO Index: 1
11.06 18:32:42 [Server] INFO Listeners:
11.06 18:32:42 [Server] INFO 0: NORMAL
11.06 18:32:42 [Server] INFO 1: ASM: class moguns.events.RecoilShootingEvent recoil(Lcom/mrcrayfish/guns/event/GunFireEvent$Post;)V
11.06 18:32:42 [Server] INFO 2: ASM: class moguns.events.PistolEmptyEvent postShoot(Lcom/mrcrayfish/guns/event/GunFireEvent$Post;)V
11.06 18:32:42 [Server] INFO 3: ASM: class moguns.events.GarandPingEvent postShoot(Lcom/mrcrayfish/guns/event/GunFireEvent$Post;)V
11.06 18:32:42 [Server] INFO java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
11.06 18:32:42 [Server] INFO at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
11.06 18:32:42 [Server] INFO at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
11.06 18:32:42 [Server] INFO at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
11.06 18:32:42 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
11.06 18:32:42 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
11.06 18:32:42 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
11.06 18:32:42 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
11.06 18:32:42 [Server] INFO at com.mrcrayfish.guns.client.handler.RecoilHandler.getAdsRecoilReduction(RecoilHandler.java:129)
11.06 18:32:42 [Server] INFO at moguns.events.RecoilShootingEvent.recoil(RecoilShootingEvent.java:52)
11.06 18:32:42 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler_1390_RecoilShootingEvent_recoil_Post.invoke(.dynamic)
11.06 18:32:42 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
11.06 18:32:42 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
11.06 18:32:42 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
11.06 18:32:42 [Server] INFO at com.mrcrayfish.guns.common.network.ServerPlayHandler.handleShoot(ServerPlayHandler.java:128)
11.06 18:32:42 [Server] INFO at com.mrcrayfish.guns.network.message.MessageShoot.lambda$handle$0(MessageShoot.java:49)
11.06 18:32:42 [Server] INFO at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215)
11.06 18:32:42 [Server] INFO at com.mrcrayfish.guns.network.message.MessageShoot.handle(MessageShoot.java:44)
11.06 18:32:42 [Server] INFO at com.mrcrayfish.guns.network.PacketHandler.lambda$registerPlayMessage$7(PacketHandler.java:71)
11.06 18:32:42 [Server] INFO at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128)
11.06 18:32:42 [Server] INFO at java.util.Optional.ifPresent(Optional.java:159)
11.06 18:32:42 [Server] INFO at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128)
11.06 18:32:42 [Server] INFO at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162)
11.06 18:32:42 [Server] INFO at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80)
11.06 18:32:42 [Server] INFO at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
11.06 18:32:42 [Server] INFO at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
11.06 18:32:42 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
11.06 18:32:42 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
11.06 18:32:42 [Server] INFO at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86)
11.06 18:32:42 [Server] INFO at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91)
11.06 18:32:42 [Server] INFO at java.util.Optional.map(Optional.java:215)
11.06 18:32:42 [Server] INFO at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91)
11.06 18:32:42 [Server] INFO at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413)
11.06 18:32:42 [Server] INFO at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42)
11.06 18:32:42 [Server] INFO at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12)
11.06 18:32:42 [Server] INFO at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
11.06 18:32:42 [Server] INFO at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
11.06 18:32:42 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
11.06 18:32:42 [Server] INFO at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
11.06 18:32:42 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734)
11.06 18:32:42 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159)
11.06 18:32:42 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
11.06 18:32:42 [Server] INFO at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717)
11.06 18:32:42 [Server] INFO at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711)
11.06 18:32:42 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
11.06 18:32:42 [Server] INFO at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697)
11.06 18:32:42 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646)
11.06 18:32:42 [Server] INFO at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
11.06 18:32:42 [Server] INFO at java.lang.Thread.run(Thread.java:748)
11.06 18:32:42 [Server] Server thread/FATAL [minecraft/ThreadTaskExecutor]: Error executing task on Server
11.06 18:32:42 [Server] INFO java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
11.06 18:32:42 [Server] INFO at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[custom.jar:36.2] {}
11.06 18:32:42 [Server] INFO at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?] {}
11.06 18:32:42 [Server] INFO at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?] {}
11.06 18:32:42 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?] {}
11.06 18:32:42 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?] {re:classloading}
11.06 18:32:42 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
11.06 18:32:42 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312] {}
11.06 18:32:42 [Server] INFO at com.mrcrayfish.guns.client.handler.RecoilHandler.getAdsRecoilReduction(RecoilHandler.java:129) ~[cgm:1.2.5-1.16.5] {re:classloading}
11.06 18:32:42 [Server] INFO at moguns.events.RecoilShootingEvent.recoil(RecoilShootingEvent.java:52) ~[moguns:1.5-1.16.5] {re:classloading}
11.06 18:32:42 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler_1390_RecoilShootingEvent_recoil_Post.invoke(.dynamic) ~[?:?] {}
11.06 18:32:42 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
11.06 18:32:42 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
11.06 18:32:42 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
11.06 18:32:42 [Server] INFO at com.mrcrayfish.guns.common.network.ServerPlayHandler.handleShoot(ServerPlayHandler.java:128) ~[cgm:1.2.5-1.16.5] {re:classloading}
11.06 18:32:42 [Server] INFO at com.mrcrayfish.guns.network.message.MessageShoot.lambda$handle$0(MessageShoot.java:49) ~[cgm:1.2.5-1.16.5] {re:classloading}
11.06 18:32:42 [Server] INFO at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[forge:?] {re:classloading}
11.06 18:32:42 [Server] INFO at com.mrcrayfish.guns.network.message.MessageShoot.handle(MessageShoot.java:44) ~[cgm:1.2.5-1.16.5] {re:classloading}
11.06 18:32:42 [Server] INFO at com.mrcrayfish.guns.network.PacketHandler.lambda$registerPlayMessage$7(PacketHandler.java:71) ~[cgm:1.2.5-1.16.5] {re:mixin,re:classloading}
11.06 18:32:42 [Server] INFO at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge:?] {re:classloading}
11.06 18:32:42 [Server] INFO at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_312] {}
11.06 18:32:42 [Server] INFO at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge:?] {re:classloading}
11.06 18:32:42 [Server] INFO at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?] {re:classloading}
11.06 18:32:42 [Server] INFO at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:SimpleChannelMixin,pl:mixin:A}
11.06 18:32:42 [Server] INFO at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
11.06 18:32:42 [Server] INFO at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
11.06 18:32:42 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
11.06 18:32:42 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
11.06 18:32:42 [Server] INFO at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[forge:?] {re:classloading}
11.06 18:32:42 [Server] INFO at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[forge:?] {re:classloading}
11.06 18:32:42 [Server] INFO at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_312] {}
11.06 18:32:42 [Server] INFO at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[forge:?] {re:classloading}
11.06 18:32:42 [Server] INFO at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,pl:mixin:A}
11.06 18:32:42 [Server] INFO at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:connectivity.mixins.json:networkstats.CCustomPayloadPacketNameMixin,pl:mixin:A,pl:runtimedistcleaner:A}
11.06 18:32:42 [Server] INFO at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:connectivity.mixins.json:networkstats.CCustomPayloadPacketNameMixin,pl:mixin:A,pl:runtimedistcleaner:A}
11.06 18:32:42 [Server] INFO at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:mixin,re:classloading}
11.06 18:32:42 [Server] INFO at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
11.06 18:32:42 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
11.06 18:32:42 [Server] INFO at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}

I attached the full log below
[latest (1).log](https://github.com/MrCrayfish/MrCrayfishGunMod/files/8884552/latest.1.log)

**Comment by MrCrayfish** [comment]
Log points to Mo Guns, not this mod.
