### ISSUE TITLE
Unable to Fire Single-Fire Guns properly... (What am I, stupid?)

### ISSUE THREAD

**Issue by MinerB4** [MrCrayfish/MrCrayfishGunMod#304]
I don't know what is happening but when I try to fire any **single-fire gun** it doesn't, but **automatic guns** will work.
What's even weirder is that this works just fine with a **Controller**...

I do have other mods installed, however these should not conflict.

- Ambient Environment
- AmbientSounds 5
- ArmorPoints ++ / HealthStacking
- AttributeFix
- Balm
- Better Ping Display
- Bookshelf
- Catalogue
- Client Tweaks
- Configured
- Controllable
- Controlling
- Creative Core
- Enchantment Descriptions
- EnhancedVisuals
- Entity Culling
- Framework
- Game Menu Mod Option
- Jade
- MrCrayfish's Furniture Mod
- **MrCrayfish's Gun Mod**
- Physics Mod
- Re-chiseled
- Sound Physics Remastered
- SuperMartijn642's Config Lib
- SuperMartijn642's Core Lib

Later I took out every mod except for CGM, Framework, and Controllable. I actually found out in this test that the guns do work!
_When you switch to another gun while firing the gun..._

Footage: https://youtu.be/cHt4Sx6dEu4

**Comment by MrCrayfish** [comment]
Installed mods 1 to 1 and it worked fine. I recommend to test using latest version of Forge.

**Comment by MinerB4** [comment]
I would say that at the time I posted this the latest version of Forge was 41.0.26... I will try again and see if it works.

**Comment by MinerB4** [comment]
I forgot to mention that this issue takes place in cgm-1.2.7-1.19.jar (Provided by CurseForge App)
The issue persists and still cannot fire single-fire guns properly...
I don't even know how this could even happen...

**Comment by MinerB4** [comment]
Alright, I am going to close this because I think the profile I was running had issues. , I just started a new profile with the mod and it now works correctly... I still have no clue what happened.
