### ISSUE TITLE
Invisible weapons.

### ISSUE THREAD

**Issue by RyanDavanzo** [MrCrayfish/MrCrayfishGunMod#305]
Uhm..the weapons are invisible ;w;

**Comment by MrCrayfish** [comment]
No they're not.

**Comment by MrCrayfish** [comment]
Send me mod list, screenshots, etc

**Comment by RyanDavanzo** [comment]
![image](https://user-images.githubusercontent.com/85040318/173916215-3088454c-2b6e-45e5-a58b-5ae00dccf8c6.png)
![image](https://user-images.githubusercontent.com/85040318/173916265-aa75aff3-a8c0-4c5d-b2b1-f6179d04d76f.png)

**Comment by MrCrayfish** [comment]
According to the mod list you don't even have my gun mod installed. "Old Guns" is not mine lol

**Comment by RyanDavanzo** [comment]
old guns is another mod. and i had yours deactvated...
