### ISSUE TITLE
Incompatibility with Corpse, Lootable Bodies, etc. after 0.14.0

### ISSUE THREAD

**Issue by happybandit360** [MrCrayfish/MrCrayfishGunMod#31]
After extensive testing we discovered a strange incompatibility between MrCrayfish's Gun Mod and mods like Corpse and DrCyano's Lootable Bodies. When the gun mod is installed, the inventories of the graves created by these mods are empty. When the game is reloaded with the gun mod disabled, you can recover the items without any other changes. We reverted the gun mod to version 0.14.0 and found they worked together at that version. There is no information in the console to indicate what is causing the issue. We just wanted to make you aware of the issue, as we're not sure what else might be effected.

**Comment by MrCrayfish** [comment]
I've done the research and this is a tricky situation beause yes my mod does cause the issue but it's poor coding on their end that contibute to the problem. 

Mods should only open their container on the server side, however many mods run the code client and server. The running it on both sides causes the GUI to be opened twice. You will noticed on a high ping server when you open a lootable body that that the slots will be blank then a second later the items will appear. If it was only called on the server side then when the GUI is opened, the items will be there straight away.

I will look into work around that I can implement. This wouldn't be a problem if the mods you're having the problem with only opened them server side.

**Comment by happybandit360** [comment]
I greatly appreciate you responding, and I totally understand the situation.

**Comment by JoelZBub** [comment]
https://www.curseforge.com/minecraft/mc-mods/corpse/issues/12

**Comment by MrCrayfish** [comment]
Unknown if this is still an issue in modern versions. Create a new issue if it still exists.
