### ISSUE TITLE
I cant shoot some of the guns

### ISSUE THREAD

**Issue by sky215** [MrCrayfish/MrCrayfishGunMod#310]
as the title said i cant shoot some of the guns like awm,bazooka,granade launchers and a few others

**Comment by tweeleaf** [comment]
i have the same problem with the same guns. i think it’s a thing with the 1.18.2 version.

**Comment by sky215** [comment]
> i have the same problem with the same guns. i think it’s a thing with the 1.18.2 version.

im using the 1.16.5 version

**Comment by MinerB4** [comment]
I had the same issue in 1.19, for some reason I think there was a mod installed that overwrote or corrupted some code for manual/semi-automatic guns.
EDIT: I am so confused now.

**Comment by MrCrayfish** [comment]
Fix coming soon for 1.18.2 and above

**Comment by kcraptor82** [comment]
> Fix coming soon for 1.18.2 and above

Seen this on the other related posts, so can this be fixed in 1.16.5? This issue has been a problem for over 2 years. Some of us like to use the attack / place buttons inverted.
