### ISSUE TITLE
 i cant see the gun

### ISSUE THREAD

**Issue by cristithegithubber** [MrCrayfish/MrCrayfishGunMod#317]
the gun is invisible
![image](https://user-images.githubusercontent.com/108936417/177991822-a44d896a-1eee-4c5d-92f2-63349df479dd.png)
![image](https://user-images.githubusercontent.com/108936417/177991900-205edffb-285e-432a-a15f-cc3baa10e645.png)

**Comment by MrCrayfish** [comment]
This can temporarily be fixed by turning graphics to anything besides Fabulous

**Comment by saltdevanimator** [comment]
happened to me aswell and was fixed by turning graphics to fancy

**Comment by MrCrayfish** [comment]
Fixed in upcoming 1.18.2 update

**Comment by saltdevanimator** [comment]
I'm using the 1.16.5 version, can you make an updated version of that one
if you can?
