### ISSUE TITLE
Incompatibility with Ice and Fire mounts

### ISSUE THREAD

**Issue by Chromaskunk** [MrCrayfish/MrCrayfishGunMod#32]
Mods used:
LLibrary 1.7.19
Ice and Fire 1.8.1
Obfuscate 0.2.6
MrCrayfish's Gun Mod 0.15.2

With only those mods installed, I cannot fly upwards and have great difficulty initiating flying with dragon mounts or hippogryphs.  Additionally, I cannot un-mount a hippocampus by sneaking and have to save and quit to dismount.  
Rolling Ice and Fire back to 1.8.0 has similar results, but dragons are able to fly in that version with the other two mounts still being broken.

Turning off the gun mod fixes all issues.

**Comment by Betarabbit14** [comment]
Going into config files and changing `B:"Use Old Controls"=true` solves mounting issues but you can no longer aim to shoot.
