### ISSUE TITLE
Suggestion: make scopes use amethyst instead of glass panes

### ISSUE THREAD

**Issue by Ch1216** [MrCrayfish/MrCrayfishGunMod#320]
I think it makes more sense to use amethyst since amethyst is used for spyglass and that zooms, and since scopes zoom they should use amethyst

Maybe the short scope wouldn't use a amethyst since it doesn't seem to do any actual zooming but at the end it does zoom in the camera; the long scope would use more since it zooms in more than other 2 scopes

[MrCrayfish Gun Mod Amethyst Scope Recipe.zip](https://github.com/MrCrayfish/MrCrayfishGunMod/files/9095025/MrCrayfish.Gun.Mod.Amethyst.Scope.Recipe.zip)
Here a datapack I made that changes the recipes

( suggestion styled/inspired after #222 )

**Comment by saltdevanimator** [comment]
makes sense, since blaze juice and ender sap arent just some random materials he made up
they're made from mobs from the game

**Comment by MrCrayfish** [comment]
I've applied these changes. Thanks for the idea.
