### ISSUE TITLE
Mod fails to load on Forge Version 41.0.98

### ISSUE THREAD

**Issue by august54742** [MrCrayfish/MrCrayfishGunMod#321]
Game won't load with error java.lang.reflect.InvocationTargetException: null and I have framework v0.3.1 giving the same error
<img width="590" alt="error" src="https://user-images.githubusercontent.com/109191670/178636696-1e49eea0-eb82-4a4a-830d-0b128a2d78ba.png">

**Comment by Scribeseer** [comment]
i got the same issue it keeps saying failed to load correctly it sucks i was really hoping to mess around with the mod
:( 
also if you figured it out please tell me

**Comment by Scribeseer** [comment]
@august54742 
The newest update fixed the problem

**Comment by august54742** [comment]
Oh it does work now, thanks
