### ISSUE TITLE
The ?7java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by Scribeseer** [MrCrayfish/MrCrayfishGunMod#322]
Framework (framework) has failed to load correctly
?7java.lang.reflect.InvocationTargetException: null,
        MrCrayfish's Gun Mod (cgm) has failed to load correctly
?7java.lang.reflect.InvocationTargetException: null 
HOW DO I FIX THIS PLEASE HELP I REALLY WANNA MESS AROUND WITH THE MOD :(

**Comment by MrCrayfish** [comment]
Duplicate of https://github.com/MrCrayfish/MrCrayfishGunMod/issues/321
