### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by leoj0720** [MrCrayfish/MrCrayfishGunMod#323]
In 1.19 Forge 41.0.63, I put the cgm mod in, but the game quits. The game error remains. Even after removing all other mods, the error remains.

**Comment by notkrispcode** [comment]
Try installing framework mod its required to run cgm

**Comment by notkrispcode** [comment]
For some reason 1.19 cgm is crashing without it instead of forge telling you that you need it like normal

**Comment by MrCrayfish** [comment]
To use the latest version on 1.19, you will need to use Forge 41.0.94 or higher. You can't use an older version.
