### ISSUE TITLE
Crash when rendering guns 1.18.1

### ISSUE THREAD

**Issue by OposDev** [MrCrayfish/MrCrayfishGunMod#324]
Hello, 

I'm not sure if there is a specific place for discussion or questions so I'm creating an issue here. 

I'm a server owner & modpack dev and some of my players have been running into a bug with this mod, it seems to happen with players that have AMD graphics. 
[crash-2022-07-17_22.33.54-client.txt](https://github.com/MrCrayfish/MrCrayfishGunMod/files/9129372/crash-2022-07-17_22.33.54-client.txt)

I noticed that there was a commit for a similar (or maybe exact same?) bug here 
https://github.com/MrCrayfish/MrCrayfishGunMod/issues/262
https://github.com/MrCrayfish/MrCrayfishGunMod/commit/6fb2c61770d664407c46bead8bb9021ded5d79e6
but my server is on 1.18.1 

Is this bug fixed in Gun Mod 1.2.1? Is there a source build for 1.2.1? 

I'm not sure if I can upgrade the server to 1.18.2 as the modpack is pretty massive (over 170 mods) and it would take a lot of time to migrate.

**Comment by MrCrayfish** [comment]
Update to 1.18.2, not patching my mods on unsupported minor versions of Minecraft. Basically if you install 170 mods, you are going to be stuck on that version forever and mod authors don't have the time to create updated versions of their mods for every version of the game.
