### ISSUE TITLE
Friend's game keeps crashing after using rpg

### ISSUE THREAD

**Issue by Joshuam303** [MrCrayfish/MrCrayfishGunMod#33]
My friend's game crashed after using the RPG and now he can't connect 

	---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22 (2).jar)
  CorePlugin (AcademyCraft-1.1.2.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  CreativePatchingLoader (CreativeCore_v1.9.44_mc1.12.2.jar)
  MixinLoaderForge (Valkyrien+Warfare+0.9_prerelease_5+[Optimization+Update].jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  pymtech (PymTech-1.12.2-1.0.2.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.8 (1).jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre135_mc1.12.2 (1).jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 10/6/19 11:37 AM
Description: Initializing game

java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:76)
	at java.awt.image.Raster.createPackedRaster(Raster.java:467)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at sun.awt.image.ImageRepresentation.createBufferedImage(ImageRepresentation.java:253)
	at sun.awt.image.ImageRepresentation.setPixels(ImageRepresentation.java:362)
	at java.awt.image.ReplicateScaleFilter.setPixels(ReplicateScaleFilter.java:209)
	at sun.awt.image.OffScreenImageSource.sendPixels(OffScreenImageSource.java:102)
	at sun.awt.image.OffScreenImageSource.produce(OffScreenImageSource.java:187)
	at sun.awt.image.OffScreenImageSource.addConsumer(OffScreenImageSource.java:66)
	at sun.awt.image.OffScreenImageSource.startProduction(OffScreenImageSource.java:80)
	at java.awt.image.FilteredImageSource.startProduction(FilteredImageSource.java:183)
	at sun.awt.image.ImageRepresentation.startProduction(ImageRepresentation.java:732)
	at sun.awt.image.ToolkitImage.addWatcher(ToolkitImage.java:221)
	at sun.awt.image.ToolkitImage.getWidth(ToolkitImage.java:110)
	at cam72cam.immersiverailroading.render.OBJTextureSheet$SubTexture.convertToBufferedImage(OBJTextureSheet.java:128)
	at cam72cam.immersiverailroading.render.OBJTextureSheet$SubTexture.resize(OBJTextureSheet.java:146)
	at cam72cam.immersiverailroading.render.OBJTextureSheet.<init>(OBJTextureSheet.java:320)
	at cam72cam.immersiverailroading.render.OBJRender.<init>(OBJRender.java:29)
	at cam72cam.immersiverailroading.render.entity.StockModel.<init>(StockModel.java:38)
	at cam72cam.immersiverailroading.render.StockRenderCache.getRender(StockRenderCache.java:79)
	at cam72cam.immersiverailroading.render.StockRenderCache.tryPrimeRenderCache(StockRenderCache.java:55)
	at cam72cam.immersiverailroading.render.StockRenderCache.tryPrime(StockRenderCache.java:93)
	at cam72cam.immersiverailroading.proxy.ClientProxy.afterTextureStitch(ClientProxy.java:414)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_443_ClientProxy_afterTextureStitch_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPost(ForgeHooksClient.java:218)
	at net.minecraft.client.renderer.texture.TextureMap.finishLoading(TextureMap.java:263)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:112)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:91)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:76)
	at java.awt.image.Raster.createPackedRaster(Raster.java:467)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at sun.awt.image.ImageRepresentation.createBufferedImage(ImageRepresentation.java:253)
	at sun.awt.image.ImageRepresentation.setPixels(ImageRepresentation.java:362)
	at java.awt.image.ReplicateScaleFilter.setPixels(ReplicateScaleFilter.java:209)
	at sun.awt.image.OffScreenImageSource.sendPixels(OffScreenImageSource.java:102)
	at sun.awt.image.OffScreenImageSource.produce(OffScreenImageSource.java:187)
	at sun.awt.image.OffScreenImageSource.addConsumer(OffScreenImageSource.java:66)
	at sun.awt.image.OffScreenImageSource.startProduction(OffScreenImageSource.java:80)
	at java.awt.image.FilteredImageSource.startProduction(FilteredImageSource.java:183)
	at sun.awt.image.ImageRepresentation.startProduction(ImageRepresentation.java:732)
	at sun.awt.image.ToolkitImage.addWatcher(ToolkitImage.java:221)
	at sun.awt.image.ToolkitImage.getWidth(ToolkitImage.java:110)
	at cam72cam.immersiverailroading.render.OBJTextureSheet$SubTexture.convertToBufferedImage(OBJTextureSheet.java:128)
	at cam72cam.immersiverailroading.render.OBJTextureSheet$SubTexture.resize(OBJTextureSheet.java:146)
	at cam72cam.immersiverailroading.render.OBJTextureSheet.<init>(OBJTextureSheet.java:320)
	at cam72cam.immersiverailroading.render.OBJRender.<init>(OBJRender.java:29)
	at cam72cam.immersiverailroading.render.entity.StockModel.<init>(StockModel.java:38)
	at cam72cam.immersiverailroading.render.StockRenderCache.getRender(StockRenderCache.java:79)
	at cam72cam.immersiverailroading.render.StockRenderCache.tryPrimeRenderCache(StockRenderCache.java:55)
	at cam72cam.immersiverailroading.render.StockRenderCache.tryPrime(StockRenderCache.java:93)
	at cam72cam.immersiverailroading.proxy.ClientProxy.afterTextureStitch(ClientProxy.java:414)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_443_ClientProxy_afterTextureStitch_Post.invoke(.dynamic)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:383)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 195158232 bytes (186 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 94 mods loaded, 94 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                   | Version               | Source                                                                 | Signature                                |
	|:----- |:------------------------------------ |:--------------------- |:---------------------------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                            | 1.12.2                | minecraft.jar                                                          | None                                     |
	| LCH   | mcp                                  | 9.42                  | minecraft.jar                                                          | None                                     |
	| LCH   | FML                                  | 8.0.99.99             | forge-1.12.2-14.23.5.2847.jar                                          | None                                     |
	| LCH   | forge                                | 14.23.5.2847          | forge-1.12.2-14.23.5.2847.jar                                          | None                                     |
	| LCH   | LambdaLib|Core                       | 0.1.9                 | minecraft.jar                                                          | None                                     |
	| LCH   | creativecoredummy                    | 1.0.0                 | minecraft.jar                                                          | None                                     |
	| LCH   | littletilescore                      | 1.0.0                 | minecraft.jar                                                          | None                                     |
	| LCH   | obfuscate                            | 0.2.6                 | minecraft.jar                                                          | None                                     |
	| LCH   | srm-hooks                            | 1.12.2-1.0.0          | minecraft.jar                                                          | None                                     |
	| LCH   | securitycraft                        | v1.8.12               | [1.12.2]+SecurityCraft+v1.8.12.jar                                     | None                                     |
	| LCH   | lambdalib2                           | 0.1.9                 | AcademyCraft-1.1.2.jar                                                 | None                                     |
	| LCH   | academy                              | 1.1.2                 | AcademyCraft-1.1.2.jar                                                 | None                                     |
	| LCH   | aoa3                                 | 3.1.1                 | AoA3-3.1.1.jar                                                         | None                                     |
	| LCH   | baubles                              | 1.5.2                 | Baubles-1.12-1.5.2 (2).jar                                             | None                                     |
	| LCH   | bettercombatmod                      | 1.5.6                 | BetterCombat-1.12.2-1.5.6.jar                                          | None                                     |
	| LCH   | betterquesting                       | 3.5.312               | BetterQuesting-3.5.312.jar                                             | None                                     |
	| LCH   | bibliocraft                          | 2.4.5                 | BiblioCraft[v2.4.5][MC1.12.2] (1).jar                                  | None                                     |
	| LCH   | mts                                  | 15.0.0                | Immersive+Vehicles-1.12.2-15.0.0.jar                                   | None                                     |
	| LCH   | unuparts                             | 2.1.1                 | UNU+Parts+Pack+[MTS]+[IR]+1.12.2-15.0.0-1.5.0-2.1.1.jar                | None                                     |
	| LCH   | btcivil                              | 2.2.1                 | BlackThorne+Civilian+Vehicles+[MTS]+[IR]+1.12.2-15.0.0-1.5.0-2.2.1.jar | None                                     |
	| LCH   | casinocraft                          | v06                   | CasinoCraft_1.12.2_v06.jar                                             | None                                     |
	| LCH   | cfm                                  | 6.2.0                 | cfm-6.2.0-mc1.12.2.jar                                                 | None                                     |
	| LCH   | cgm                                  | 0.11.0                | cgm-0.11.0-mc1.12.2.jar                                                | None                                     |
	| LCH   | ctm                                  | MC1.12.2-0.3.3.22     | CTM-MC1.12.2-0.3.3.22 (2).jar                                          | None                                     |
	| LCH   | chisel                               | MC1.12.2-0.2.1.35     | Chisel-MC1.12.2-0.2.1.35 (2).jar                                       | None                                     |
	| LCH   | corpse                               | 1.12.2-1.0.1          | corpse-1.12.2-1.0.1.jar                                                | None                                     |
	| LCH   | cosmeticarmorreworked                | 1.12.2-v4             | CosmeticArmorReworked-1.12.2-v4.jar                                    | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCH   | cosmeticarmorreworked|tombmanygraves | 1.12.2-v4             | CosmeticArmorReworked-1.12.2-v4.jar                                    | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCH   | craftstudioapi                       | 1.0.0                 | CraftStudio-1.0.0.93-mc1.12-alpha.jar                                  | None                                     |
	| LCH   | creativecore                         | 1.9.9                 | CreativeCore_v1.9.44_mc1.12.2.jar                                      | None                                     |
	| LCH   | modcurrency                          | 1.12-1.3.11           | Currency-1.12.0-1.3.11.jar                                             | None                                     |
	| LCH   | customnpcs                           | 1.12                  | CustomNPCs_1.12.2(30Jan19).jar                                         | None                                     |
	| LCH   | cyberware                            | 0.2.11.20             | cyberware-1.12.2-0.2.11.20.jar                                         | None                                     |
	| LCH   | ptrmodellib                          | 1.0.4                 | PTRLib-1.0.4.jar                                                       | None                                     |
	| LCH   | props                                | 2.6.3                 | Decocraft-2.6.3_1.12.2.jar                                             | None                                     |
	| LCH   | dfheroesexpansion                    | 1.3                   | DFHeroesExpansion 1.3(non restricted forge).jar                        | None                                     |
	| LCH   | drones                               | 0.3.1                 | Drones-0.3.1.jar                                                       | None                                     |
	| LCH   | ebwizardry                           | 4.1.4                 | Electroblob's+Wizardry+-+4.1.4+-+MC+1.12.2.jar                         | None                                     |
	| LCH   | extra_spells                         | 1.0.7                 | ExtraSpells-1.12.2-1.0.7.jar                                           | None                                     |
	| LCH   | jei                                  | 4.15.0.268            | jei_1.12.2-4.15.0.268 (1).jar                                          | None                                     |
	| LCH   | ftblib                               | 5.4.1.97              | FTBLib-5.4.1.97 (1).jar                                                | None                                     |
	| LCH   | ftbutilities                         | 5.4.0.95              | FTBUtilities-5.4.0.95 (1).jar                                          | None                                     |
	| LCH   | heroesarrival                        | 1.0.0                 | Heroes+Arrival+1.2.1.jar                                               | None                                     |
	| LCH   | ironman                              | Beta-1.12.2-1.2.6     | IronMan-1.12.2-Beta-1.12.2-1.2.6.jar                                   | None                                     |
	| LCH   | speedsterheroes                      | 1.12.2-2.1.4          | SpeedsterHeroes-1.12.2-2.1.4.jar                                       | None                                     |
	| LCH   | lucraftcore                          | 1.12.2-2.4.8          | LucraftCore-1.12.2-2.4.8 (1).jar                                       | None                                     |
	| LCH   | heroesexpansion                      | 1.12.2-1.3.5          | HeroesExpansion-1.12.2-1.3.5.jar                                       | None                                     |
	| LCH   | ichunutil                            | 7.2.1                 | iChun-Util-Mod-1.12.2 (1).jar                                          | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | trackapi                             | 1.1                   | TrackAPI-1.1_1.12.jar                                                  | None                                     |
	| LCH   | immersiverailroading                 | 1.6.0                 | ImmersiveRailroading-1.6.0_1.12-1135 (1).jar                           | None                                     |
	| LCH   | ironchest                            | 1.12.2-7.0.59.842     | ironchest-1.12.2-7.0.59.842 (1).jar                                    | None                                     |
	| LCH   | journeymap                           | 1.12.2-5.5.5          | journeymap-1.12.2-5.5.5.jar                                            | None                                     |
	| LCH   | littletiles                          | 1.5.0                 | LittleTiles_v1.5.0-pre135_mc1.12.2 (1).jar                             | None                                     |
	| LCH   | lycanitesmobs                        | 1.20.5.3 - MC 1.12.2  | LycanitesMobsComplete+1.20.5.3+[1.12.2].jar                            | None                                     |
	| LCH   | arcticmobs                           | 1.20.5.3 - MC 1.12.2  | LycanitesMobsComplete+1.20.5.3+[1.12.2].jar                            | None                                     |
	| LCH   | demonmobs                            | 1.20.5.3 - MC 1.12.2  | LycanitesMobsComplete+1.20.5.3+[1.12.2].jar                            | None                                     |
	| LCH   | desertmobs                           | 1.20.5.3 - MC 1.12.2  | LycanitesMobsComplete+1.20.5.3+[1.12.2].jar                            | None                                     |
	| LCH   | elementalmobs                        | 1.20.5.3 - MC 1.12.2  | LycanitesMobsComplete+1.20.5.3+[1.12.2].jar                            | None                                     |
	| LCH   | forestmobs                           | 1.20.5.3 - MC 1.12.2  | LycanitesMobsComplete+1.20.5.3+[1.12.2].jar                            | None                                     |
	| LCH   | freshwatermobs                       | 1.20.5.3 - MC 1.12.2  | LycanitesMobsComplete+1.20.5.3+[1.12.2].jar                            | None                                     |
	| LCH   | infernomobs                          | 1.20.5.3 - MC 1.12.2  | LycanitesMobsComplete+1.20.5.3+[1.12.2].jar                            | None                                     |
	| LCH   | junglemobs                           | 1.20.5.3 - MC 1.12.2  | LycanitesMobsComplete+1.20.5.3+[1.12.2].jar                            | None                                     |
	| LCH   | mountainmobs                         | 1.20.5.3 - MC 1.12.2  | LycanitesMobsComplete+1.20.5.3+[1.12.2].jar                            | None                                     |
	| LCH   | plainsmobs                           | 1.20.5.3 - MC 1.12.2  | LycanitesMobsComplete+1.20.5.3+[1.12.2].jar                            | None                                     |
	| LCH   | saltwatermobs                        | 1.20.5.3 - MC 1.12.2  | LycanitesMobsComplete+1.20.5.3+[1.12.2].jar                            | None                                     |
	| LCH   | shadowmobs                           | 1.20.5.3 - MC 1.12.2  | LycanitesMobsComplete+1.20.5.3+[1.12.2].jar                            | None                                     |
	| LCH   | swampmobs                            | 1.20.5.3 - MC 1.12.2  | LycanitesMobsComplete+1.20.5.3+[1.12.2].jar                            | None                                     |
	| LCH   | malisiscore                          | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                                           | None                                     |
	| LCH   | malisisdoors                         | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                                          | None                                     |
	| LCH   | radixcore                            | 1.12.x-2.2.1          | RadixCore-1.12.x-2.2.1-universal (2).jar                               | None                                     |
	| LCH   | mca                                  | 1.12.2-5.3.1          | MCA-1.12.x-5.3.1-universal.jar                                         | None                                     |
	| LCH   | mobbattle                            | 2.3.2                 | MobBattleMod-1.12.2-2.3.2.jar                                          | None                                     |
	| LCH   | numina                               | 1.12.2-1.0.36         | Numina-Mod-1.12.2.jar                                                  | None                                     |
	| LCH   | powersuits                           | 1.12.2-1.0.40         | ModularPowersuits-1.12.2-1.0.40.jar                                    | None                                     |
	| LCH   | morph                                | 7.1.3                 | Morphing-Mod-1.12.2.jar                                                | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | mam                                  | 1.0                   | MystAdditions-1.0.jar                                                  | None                                     |
	| LCH   | harvestcraft                         | 1.12.2zb              | Pam's+HarvestCraft+1.12.2zc+The+7mm+Kidney+Stone+Update.jar            | None                                     |
	| LCH   | pymtech                              | 1.12.2-1.0.2          | PymTech-1.12.2-1.0.2.jar                                               | None                                     |
	| LCH   | rewired                              | 1.12.2                | ReWIRED-1.0.6.jar                                                      | None                                     |
	| LCH   | sdrones                              | 1.3.1                 | sdrones-1.3.1.jar                                                      | None                                     |
	| LCH   | secretroomsmod                       | 5.6.4                 | secretroomsmod-1.12.2-5.6.4.jar                                        | None                                     |
	| LCH   | flammpfeil.slashblade                | mc1.12-r22            | SlashBlade-mc1.12-r22.jar                                              | None                                     |
	| LCH   | spartanweaponry                      | beta 1.3.1            | SpartanWeaponry-1.12.2-beta-1.3.1.jar                                  | None                                     |
	| LCH   | bq_standard                          | 3.4.167               | StandardExpansion-3.4.167.jar                                          | None                                     |
	| LCH   | tektopia                             | 1.1.0                 | tektopia-1.1.0.jar                                                     | None                                     |
	| LCH   | the-fifth-world                      | 0.4.2                 | the-fifth-world-0.4.2 (1).jar                                          | None                                     |
	| LCH   | thutcore                             | 5.19.10               | thutcore-1.12.2-5.19.10.jar                                            | None                                     |
	| LCH   | thutcore_compat                      | 1.0                   | thutcore-1.12.2-5.19.10.jar                                            | None                                     |
	| LCH   | thuttech                             | 6.1.5                 | thuttech-1.12.2-6.1.5.jar                                              | None                                     |
	| LCH   | torohealthmod                        | 1.12.2-11             | torohealth-1.12.2-11 (1).jar                                           | None                                     |
	| LCH   | valkyrienwarfare                     | 0.9_prerelease_5      | Valkyrien+Warfare+0.9_prerelease_5+[Optimization+Update].jar           | 8f639e7b2d1117d8f2c5d545e2231f0a0519f0ce |
	| LCH   | vehicle                              | 0.39.0                | vehicle-mod-0.39.0-1.12.2.jar                                          | None                                     |
	| LCH   | xencraft                             | 1.0.0.4               | XenCraft-1.0.0.4.jar                                                   | None                                     |
	| LCH   | xlfoodmod                            | 1.12.2-1.9.0          | XL-Food-Mod-1.12.2-1.9.0.jar                                           | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22 (2).jar)
  team.chisel.ctm.client.asm.CTMTransformer
CorePlugin (AcademyCraft-1.1.2.jar)
  cn.lambdalib2.render.mc.PipelineTransformer
  cn.lambdalib2.registry.impl.RegistryTransformer
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
CreativePatchingLoader (CreativeCore_v1.9.44_mc1.12.2.jar)
  
MixinLoaderForge (Valkyrien+Warfare+0.9_prerelease_5+[Optimization+Update].jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
pymtech (PymTech-1.12.2-1.0.2.jar)
  lucraft.mods.pymtech.core.PymTechClassTransformer
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.8 (1).jar)
  lucraft.mods.lucraftcore.core.LCTransformer
LittlePatchingLoader (LittleTiles_v1.5.0-pre135_mc1.12.2 (1).jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13401 Compatibility Profile Context 15.201.1301.0' Renderer: 'AMD Radeon HD 7570M'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 7570M GL version 4.5.13401 Compatibility Profile Context 15.201.1301.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz

**Comment by MrCrayfish** [comment]
This is not an issue with my mod. Your friend is running out of RAM. "java.lang.OutOfMemoryError: Java heap space"
You'll need to get them to assign more RAM to their game.
