### ISSUE TITLE
Unexpected right click behavior on animals

### ISSUE THREAD

**Issue by DrBlocks** [MrCrayfish/MrCrayfishGunMod#34]
Hi there !
I'm experiencing an odd issue when using CGM : right clicking on horses and cows seems bugged/inefficient (cant tame/ride/feed a horse, cant properly milk a cow). It strangely messes up when you try to milk a cow or feed a horse. I checked for double binds and anything of the sort, nothing wrong for what I can see.
Is it something known or am I the first with this one ? :D

I took a video of a few behavior tests (2:31) with all reference included (mods, versions, forge version, etc). Be sure to ask if any extra info is required ;)

Awesome mod btw, with CVM, CFM and CDM, backbones of my server modpack, we enjoy those greatly !!! 👍 

https://youtu.be/UB5LHs-NyDo

**Comment by DrBlocks** [comment]
(bit later...)
Looks related to "#32 : Incompatibility with Ice and Fire mounts" issue report since Use Old Controls=true fixed the thing, but since nothing is said there about milking cows or feeding horses, i figured Id leave this here... please do merge if irrelevant ;)

**Comment by MrCrayfish** [comment]
This has been fixed in recent versions
