### ISSUE TITLE
Guns don't shoot while scoped in

### ISSUE THREAD

**Issue by trainman1351** [MrCrayfish/MrCrayfishGunMod#345]
Using my scope to aim with RMB doesn't allow me to shoot with LMB. My heavy rifle and shotgun from Additional Guns are affected, while my assault rifle is not. All dependencies are downloaded. I tried reinstalling both the original gun mod and the additional guns mod, but this didn't solve the problem. I also reset my controls. Dying and respawning seemed to fix the issue, but when it occurred, doing the same didn't work again. The problem occurred after I installed Trajan's Tank Mod, but uninstalling that mod didn't fix the issue either. I do have some other mods installed, including Optifine and Just Zoom. However, these mods were installed before I created the world, and don't appear to be causing the problem. All mods and dependencies are up to date with forge 41.1.0 and Minecraft 1.19. I will include all mod files below. System Specs (in case they are needed):
Device name	MSI
Processor	11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
Installed RAM	16.0 GB (15.7 GB usable)
System type	64-bit operating system, x64-based processor
Graphics Card  Nivida Geforce RTX 3060 Laptop GPU
[Mods.zip](https://github.com/MrCrayfish/MrCrayfishGunMod/files/9242940/Mods.zip)

Edit: I did try shooting the heavy rifle and modded shotgun in creative mode, and it worked fine, so it may be a problem with either the world or the guns themselves.

Edit 2: I tried crafting a new shotgun in the affected world, and the problem persisted. Thus, it is either a problem with crafted weapons or the world itself.

**Comment by ZolElle** [comment]
I'm having the same issue. Other players on my server can shoot fine

**Comment by MrCrayfish** [comment]
Is it only guns from that addon? If so, it's likely the problem is only in their addon. Report it to them first please.

**Comment by ZolElle** [comment]
> 

Oh I totally misread the original person's post. For me it was your guns not working while ads, except the assault rifle worked. Started working after a few days fortunately

**Comment by trainman1351** [comment]
I apologize for not replying earlier, but the heavy rifle is from the original mod. However, creating a new world and making the guns there worked, so while it isn't an ideal solution, it will have to do.

**Comment by FloppyDesk** [comment]
Hi all
I have the same problem and I found a solution.
The problem is in the shield. When it equipt guns will not shoot when sooping (aim). 
Dear MrCrayfish please cheek it and thank you for nice mod.
Have a good day 

19.2
