### ISSUE TITLE
consistent crash on 1.15.2 server when loading

### ISSUE THREAD

**Issue by FullMetalMaster** [MrCrayfish/MrCrayfishGunMod#360]
MrCrayfish's Gun Mod (cgm) encountered an error during the common_setup event phase? does this with any Forge is this fixable? 
[Gun Mod 1.0](https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod/files/3204546)

**Comment by MrCrayfish** [comment]
1.15.2 is no longer supported. Please use a modern version of Minecraft
