### ISSUE TITLE
[Suggestion] Weapon maker/buyer villager

### ISSUE THREAD

**Issue by MrNik29** [MrCrayfish/MrCrayfishGunMod#361]
There could be a villager that you can hire or not  if you hire him, you have to pay him emeralds each x days and he will produce weapons, you could upgrade your equipment so the weapons have better quality, then you can sell them to another villager far away, the more quality the weapon has the more he pays for your stock, the villager that you sell has to be far away. While you deliver, pillagers could target you to try and steal your stock, if you use a vehicle, the villager could trust you more and pay more for your stock, so that means no op elytra. Basically gta online bunker in this mod.

**Comment by alessandriLuca** [comment]
You can use the mod customTrades and custom professions to make that kind of villager
