### ISSUE TITLE
Assembly error

### ISSUE THREAD

**Issue by AlexisShinji** [MrCrayfish/MrCrayfishGunMod#362]
Hello, I was on a server with some friends and the owner did a reset, after the reset it won't let me assemble weapons or ammo, and the same happens with vehicles, the server version is 1.12.2. I hope you can tell me what I have to do to solve this

**Comment by DBSDestroyer** [comment]
Did you ever solve this issue? I'm having the same one.

**Comment by MrCrayfish** [comment]
Before I answer, I don't maintain any of my mods on 1.12.2 anymore, please update to a modern version of Minecraft if you want bugs fixed.

In the case of this, please do a full reinstall of everything. Ensure you have matching mods as the server.
