### ISSUE TITLE
Scope visual bug when game is in fullscreen mode

### ISSUE THREAD

**Issue by u12bdragon** [MrCrayfish/MrCrayfishGunMod#381]
Mod ver: 1.2.7 1.18.2
OS: Ubuntu (if that's important)
when the game is in fullscreen mode, the scopes show a still image of the last thing they "looked at" while the game was in windowed mode, instead of showing what you are actually looking at.

**Comment by MrCrayfish** [comment]
This will be fixed in 1.3.0
