### ISSUE TITLE
Weird Scope Glitch with shaders

### ISSUE THREAD

**Issue by IvorAmlug** [MrCrayfish/MrCrayfishGunMod#385]
So, Ive always grew love to this mod for its shader compat. but latley there are some issues.
The scopes have this weird "thermal" look to em
![2022-11-07_21 50 08](https://user-images.githubusercontent.com/38656481/200413213-fc25e839-f97b-4e5f-bf9c-6c0033b6806b.png)
Im using the:
Complementary Shader in this example.
As a shader provider im using Oculus (Iris Forge port)
And Rubidium (since its required by Oculus)
Mod Versions:
Forge:1.19.2 Tested with both 43.1.1 and 43.1.47
Framerwork: 0.3.3
CrayfishsGunmod:1.2.8
Oculus;1.2.8
Rubidium:0.6.2
Those are all mods required to get this issue + Any shader as far as i know...
It might be a thing with optifine too. Even tho i havent checked that yet.

**Comment by IvorAmlug** [comment]
Okay it works with optifine.
Since its only on the Rubidium Oculus Comb and only with shaders active its most likley an issue with Oculus.
I will report this to them to see if there is anything they can do about it since it worked fine before.

**Comment by SaoirseFoxspan** [comment]
Whether or not the scope has the thermal effect seems to depend on ambient light in the environment and effects that calculate light. In a dark cave with auto exposure turned off the scope is all black:
![2022-11-16_09 35 19](https://user-images.githubusercontent.com/8977288/202209956-a140321c-9850-42f4-bfb0-d4c45eb4f9ed.png)
Having auto exposure turned on while in the dark cave, however, produces the same thermal effect:
![2022-11-16_09 35 40](https://user-images.githubusercontent.com/8977288/202210321-7926d20f-a27e-4583-b07e-df72d95430f8.png)
The effect is present independent of auto exposure being on or off in a bright environment:
![2022-11-16_09 42 01](https://user-images.githubusercontent.com/8977288/202211406-8646d9d2-ce21-47b3-a4e6-051cf0785cb1.png)
Another interesting thing of note is that the scope seems to be displaying properly when ADS isn't active; however I'm unaware of the technical difference between the two states:
![2022-11-16_09 43 03](https://user-images.githubusercontent.com/8977288/202211883-185f5966-57e4-4bc9-ad33-d164fc746e4b.png)

I'm using the same shader, Complementary Shaders, within my examples.
I'm using the same shader provider: Oculus.
And it's requirement, Rubidium.
Minecraft version: 1.19.2
Mod versions:
Forge-43.1.52
CrayfishsGunMod-1.2.8
Framework-0.3.3
Oculus-1.2.8
Rubidium-0.6.2

I'd neglected to remove the MorePlayerModels mod in the screenshots, the results are the same with the mod removed, however.

**Comment by IvorAmlug** [comment]
The minecraft version dosnt matter anything from 1.16 to 1.19 has this issue with CGM its kind off sad i wanna stay on Oculus tho since its prefomantly the suppirior shader Provider.

**Comment by MrCrayfish** [comment]
This will be fixed in 1.3.0
