### ISSUE TITLE
Attachment menu opens only after pressing Attachment Open button + Left/Right Mouse Button

### ISSUE THREAD

**Issue by Foxren** [MrCrayfish/MrCrayfishGunMod#387]
Game version: 1.19.2
Mod version: 1.2.8
I can attach a video later if needed

**Comment by MrCrayfish** [comment]
Send your modpack. Works fine when I test.

**Comment by PMitzner** [comment]
Same issue for me plus i can't shoot while ADS sometimes.

**Comment by MrCrayfish** [comment]
@PMitzner Send your modpack. Works fine when I test.

**Comment by PMitzner** [comment]
[mods.zip](https://github.com/MrCrayfish/MrCrayfishGunMod/files/10031539/mods.zip)
I'm making a battle royale style pvp minigame for me and some friends on a server.

**Comment by MrCrayfish** [comment]
You downloaded my mod from unofficial sources (a website that rehosts mods, and can potential be malicious software).
Only download from my website (mrcrayfish.com) or CurseForge. I can't confirm any issues unless you use official sources.

**Comment by PotassiumMan** [comment]
I can confirm, I cannot open the attachment menu normally. The menu only opens when I use the button, and left or right click. My modpack is custom (45 mods). I downloaded the mod from curseforge, version 1.2.8, 1.19.2

**Comment by North-West-Wind** [comment]
The menu cannot be opened even with only cgm and framework.  
Update: It seems manually compiled cgm works

**Comment by MrCrayfish** [comment]
Should be fixed in an upcoming update. Reopen this if it doesn't work after 1.3.0 update.
