### ISSUE TITLE
Can’t shoot while using scope

### ISSUE THREAD

**Issue by hrt-iron** [MrCrayfish/MrCrayfishGunMod#393]
When I try to shoot while using scope, it doesn’t fire. In creative mode, I could. What should I do?

**Comment by MrCrayfish** [comment]
Send your modpack. Works fine when I test

**Comment by hrt-iron** [comment]
[hrt_cgm.zip](https://github.com/MrCrayfish/MrCrayfishGunMod/files/10040337/hrt_cgm.zip)
here's my modpack I downloaded on your website.

**Comment by hrt-iron** [comment]
I've found its cause! I had a shield on left hand, and then I can't shoot with using scope. when I have crossbow on left hand, the same occurred. Sorry for bothering you by my stupid question.
