### ISSUE TITLE
Invisible guns

### ISSUE THREAD

**Issue by KlutchGTR** [MrCrayfish/MrCrayfishGunMod#396]
![2022-11-25_10 55 53](https://user-images.githubusercontent.com/116692840/203891337-254f7733-4a88-4b08-9d2e-f33744794c6d.png)

Invisible gun....

**Comment by KlutchGTR** [comment]
This happens after few days, before it was just fine

**Comment by MrCrayfish** [comment]
Turn off Fabulous graphics (for now). Also make sure you are using the latest version of the mod
