### ISSUE TITLE
The bullets for some weapons dont move or weapon deals no damage directly

### ISSUE THREAD

**Issue by rjulib00** [MrCrayfish/MrCrayfishGunMod#398]
not gonne lie, this is a little weird to explain, but will try my best, for whatever reason, some weapon cant do any damage, but when moving somewhat fast, the bullet can be seen in the air, stuck in place just spinning, some weapons bullet fall and some others works perfectly fine (shotgun at least didnt give me any problem), i think there is something weird happening which i dont understand

its most likely due to another mod fucking it, the same way its fucking my creative and spectator mode (which for whatever reason, they allow to die and enemies still hit,but thats another story), some bullets just do whatever they want, video trying to explain all this madmind
here is the log if needed

[latest.log](https://github.com/MrCrayfish/MrCrayfishGunMod/files/10109059/latest.log)

https://youtu.be/oz0vK-hGvFI

dont know how to embed video

**Comment by MrCrayfish** [comment]
It's possible there is a mod restricting the velocity of entities (for performance reasons), which could explain why some weapons are working and some don't. The shotgun's projectile velocity is 10 blocks per tick, while the rifle is 20 blocks per tick. Your best bet is to override the gun data with a datapack and slow down the projectile speed.

Here is a template. It is designed for 1.19.2, so make sure you change the `pack_format` version to the correct one for 1.18.2
See the wiki to find the correct version: https://minecraft.fandom.com/wiki/Data_pack#Pack_format

[template_gun_datapack.zip](https://github.com/MrCrayfish/MrCrayfishGunMod/files/10372969/template_gun_datapack.2.zip)
