### ISSUE TITLE
Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by boris2255** [MrCrayfish/MrCrayfishGunMod#413]
https://mclo.gs/QeqoAxj

**Comment by SirZokxyron** [comment]
I am having the same issue out here.

**Comment by MrCrayfish** [comment]
Looking into it!

**Comment by SrRapero720** [comment]
https://mclo.gs/cVZiyKk
same issue

**Comment by MrCrayfish** [comment]
Fixed. Download 1.3.1

**Comment by SrRapero720** [comment]
its no fixed yet
https://mclo.gs/XJfltdA

![image](https://user-images.githubusercontent.com/29090346/211624315-9306a0d6-0def-4379-af1d-d826a1abe88f.png)

**Comment by SrRapero720** [comment]
![image](https://user-images.githubusercontent.com/29090346/211624787-270d65e1-8c11-4af6-8d23-43f60a251cbe.png)

**Comment by Ithko** [comment]
yeah i still have the issue too (1.3.1 version)

**Comment by The-Nyla** [comment]
I also still have this issue, please reopen the issue until it is fixed

**Comment by MrCrayfish** [comment]
Actually fixed in 1.3.2 😂
