### ISSUE TITLE
Crash upon launching instance, 1.19.2

### ISSUE THREAD

**Issue by Geekerandy** [MrCrayfish/MrCrayfishGunMod#419]
[crash-2023-01-15_00.35.51-client.txt](https://github.com/MrCrayfish/MrCrayfishGunMod/files/10419792/crash-2023-01-15_00.35.51-client.txt)

**Comment by Geekerandy** [comment]
Pastebin: https://pastebin.com/iTbTErHz

**Comment by Geekerandy** [comment]
yes, pack does start working when removing mod

**Comment by MrCrayfish** [comment]
Bug in IC2.

**Comment by Speiger** [comment]
This is fixed in the next pending patch.
It should come out in a few days.

**Comment by MrCrayfish** [comment]
@Speiger Thank you!
