### ISSUE TITLE
[Bug] [1.18.2] Incompatibility with Mine Menu.

### ISSUE THREAD

**Issue by Bongus11** [MrCrayfish/MrCrayfishGunMod#455]
The binding for the modify attachments menu doesn't work with Mine Menu at all. It simply refuses to open the menu.

**Comment by MrCrayfish** [comment]
You can change the binding in the controls

**Comment by Bongus11** [comment]
Simply changing the binding to a different key does not work, it still refuses to open that menu.

**Comment by Bongus11** [comment]
I also opened an issue on that mod's git page, and the mod creator's exact words were: "That's unfortunate.
Anything older than 1.19.4 is unsupported now."

**Comment by Bongus11** [comment]
I should also mention that I need this to work for a modpack that I'm creating so if there is no fix for this and I need to remove Mine Menu, I can. Or if you'd rather me send my mod list, I can also do that.
