### ISSUE TITLE
Incompatible with the Mod "ViveCraft"

### ISSUE THREAD

**Issue by LunarMeal** [MrCrayfish/MrCrayfishGunMod#463]
I have installed ViveCraft Mod, which is a mod that allows me to play MineCraft with VR. When I installed the module MyClayFish's Gun, I found that the model of the gun was always aimed at me, and the direction in which bullets were fired was not in the direction the gun was aimed, but in the direction my eyes were looking. Please refer to the video demonstration below for details

https://github.com/MrCrayfish/MrCrayfishGunMod/assets/60291398/43d90b09-3859-4f4a-bdb3-adcce3e7eeeb

**Comment by MrCrayfish** [comment]
The Gun Mod is only designed for the normal version of the game. No plans to support Vivecraft.

**Comment by BlueYoshi68** [comment]
Is this still the case or does a fix exist by someone else?

**Comment by BlueYoshi68** [comment]
> The Gun Mod is only designed for the normal version of the game. No plans to support Vivecraft.

Is there like...a reason for this? Are you unable to do it or something?

**Comment by MrCrayfish** [comment]
It's out of scope, that's it.

**Comment by BlueYoshi68** [comment]
So...put it in-scope? It's unimportant but if it increases compatibility then like...why wouldn't you?

**Comment by MrCrayfish** [comment]
It's not as simple as you are thinking it is otherwise support would be there. There are things that are just not important, and this is one of them. I would rather focus my time on other projects.

**Comment by BlueYoshi68** [comment]
I mean, i was able to make a modified resource that just changes the first-person model to point straight (cause evidently the bullet go where the cursor in VR is pointing despite the guns direction) which the positions and rotations themselves seem to be universal- ie one set of numbers works for every gun, all that you'd really need to is change the positions if Vivecraft is present and active

**Comment by ConnaxTheBro** [comment]
> I mean, i was able to make a modified resource that just changes the first-person model to point straight

please send, i need this

**Comment by BlueYoshi68** [comment]
i mean, mines made using the Create GUns Base, so i hope you like that XD
[Create Guns 1.2.1 - 1.19.2.zip](https://github.com/MrCrayfish/MrCrayfishGunMod/files/15211866/Create.Guns.1.2.1.-.1.19.2.zip)

**Comment by BlueYoshi68** [comment]
[ONLY ENABLE IF IN VR.zip](https://github.com/MrCrayfish/MrCrayfishGunMod/files/15211867/ONLY.ENABLE.IF.IN.VR.zip)
I mean, I made it using the Create GUns base, so none of it will look like the normal guns, so I hope you like them

**Comment by ConnaxTheBro** [comment]
oh nvm i was looking for something that works on 1.20.1, i have an unofficial port

**Comment by beejay09** [comment]
Hey @BlueYoshi68, i saw your texturepack and i love the remodels they look better than the actual guns, but would it be possible to turn the version of the texturepack to 1.20.4, or can you pls tell me how to do it?

**Comment by BlueYoshi68** [comment]
> Hey @BlueYoshi68, i saw your texturepack and i love the remodels they look better than the actual guns, but would it be possible to turn the version of the texturepack to 1.20.4, or can you pls tell me how to do it?

not mine, I just edited it so that it works in VR.

**Comment by beejay09** [comment]
for what version is it?

**Comment by beejay09** [comment]
do you also have like the edited version but with the normal guns? like the basic ones?

**Comment by BlueYoshi68** [comment]
no

**Comment by DavidYummy** [comment]
plss
