### ISSUE TITLE
[Bug] Rendering Still Issue in 1.19.2+ with First Person Model Mod

### ISSUE THREAD

**Issue by Barerock** [MrCrayfish/MrCrayfishGunMod#466]
See https://github.com/tr7zw/FirstPersonModel/issues/357

Continuous rendering bug when trying to add compatibility via AutoVanillaHand function with First Person Model.

Forge 43.2.3, 1.19.2
FPM Version 2.2.3-mc1.19.2
CGM Version 1.3.4

**Comment by MrCrayfish** [comment]
I've replied to the link issue. Unfortunately I will not be adding support as it's out of scope for the development of this mod.
