### ISSUE TITLE
request: be able to shoot endermen

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [MrCrayfish/MrCrayfishGunMod#470]
vanilla weapons don't affect endermen, but bullets are faster than arrows, can you add a feature where you can shoot endermen with guns?

**Comment by mindforger** [comment]
teleportation is instant, imho enderman should also be able to dodge bullets not only arrows

**Comment by SonicTheHedgehog58987276** [comment]
some gun mods have this feature.

**Comment by MrCrayfish** [comment]
Intentional design.

**Comment by SonicTheHedgehog58987276** [comment]
forgot to say: bullets can be faster than endermen eyes in a realistic way

**Comment by SonicTheHedgehog58987276** [comment]
thanks for fulfilling my request, mrcrayfish
