### ISSUE TITLE
Client crashes

### ISSUE THREAD

**Issue by winnieduhpoooh** [MrCrayfish/MrCrayfishGunMod#49]
My client crashes when I either leave the server or it crashes itself. When I read the crash report, it's telling me the crash is related to the Bullet tick and rendering the bullet tick. I'd like some assistance please.
Anyways, here's the crash report: https://pastebin.com/4ykGaVnu

**Comment by dragonshardz** [comment]
I am also experiencing this issue.

**Comment by winnieduhpoooh** [comment]
Realized 1.12.2 is no longer getting support
