### ISSUE TITLE
1.19.2 Datapack can't change any gun stats.

### ISSUE THREAD

**Issue by togera13** [MrCrayfish/MrCrayfishGunMod#503]
I was wondering if there was a way to adjust the gun's damage, kick, spread, firerate, reload, etc, via either a config, datapack, or something.

& if there is is there a guide anywhere? Like the main page said it supported datapacks, but I can't figure it out.

1.19.2 btw.

I tried making a data/mydatapack/cgm/guns/assault_riflejson, but I didn't see any changes to the damage number in game.

For instance, I was testing the "assault rifle" and set it to 1.5 damage & it still seems to be doing more than that, & I set the recoil really high & didn't see any change.

**Comment by MrCrayfish** [comment]
Datapacks. You almost had it right, it should be `data/cgm/guns/assault_rifle.json`

**Comment by togera13** [comment]
> Datapacks. You almost had it right, it should be `data/cgm/guns/assault_rifle.json`

THANK YOU SO MUCH! I had been struggling for so long trying to figure out where I was going wrong with my datapacks, I love you for this seriously.
