### ISSUE TITLE
NullPointerException Obfuscate w/ immersiveengineering

### ISSUE THREAD

**Issue by tofep** [MrCrayfish/MrCrayfishGunMod#51]
try to enter the game with most recent version both for obfuscate and mrcrayfish gun mod alongside the most recent version of immersive engineering and i get the following crash report:

https://paste.dimdev.org/ocizaxegel.mccrash

By the way: I'm using the engineering life modpack and could you email me at padhacks@hotmail.com to give me your opinion of what the problem is and is it more of a obfuscate problem or it could be one of the mods mentioned above that could be causing the problem?

Update: I've just visited the github for immersive engineering and the follow report was submitted: https://github.com/BluSunrize/ImmersiveEngineering/issues/3713
BluSunrize points out it isn't a IE problem and looks like the matter is closed now.

**Comment by MrCrayfish** [comment]
Unlikely to fix since 1.12.2 is now considered discontinued.
