### ISSUE TITLE
One shotting a Zombie Pigman with a gun from this mod does not cause nearby Zombie Pigmen to retaliate, but one shotting a Piglin or Piglin Brute causes nearby Piglins to retaliate.

### ISSUE THREAD

**Issue by Daralexen05** [MrCrayfish/MrCrayfishGunMod#516]
The title explains it all. One-shotting a Zombie Pigman with the firearms from this mod does not cause nearby Zombie Pigmen to retaliate, but their living counterparts do. I know that it is not that big of an issue, but it just seems inconsistent as to why Zombie PIgmen do not care when they see another member of their kind be shot in front of them, but their living counterparts do.

**Comment by Daralexen05** [comment]
It turns out that this is not an issue with this mod. It is just an oversight or issue on Minecraft's end for Zombie PIgmen AI. I tested this in Vanilla (No mods except for Optifine) with a buffed Zoglin that had strength II, and it one shotted a Zombie Pigman. The remaining Zombie Pigmen did not care.

**Comment by MrCrayfish** [comment]
Good to know.
