### ISSUE TITLE
[Bug] Certian values in datapack gun configurations cannot handle a value less than 1.

### ISSUE THREAD

**Issue by DaRealSparky** [MrCrayfish/MrCrayfishGunMod#531]
### The Problem

I am working on a data and resource pack to be used in combination with some other mods. 

During the development of the datapack, I needed to set the projectile life of the shotgun to 0.5 to achieve the effect of a sawed off style shotgun. After doing so, the datapack failed to load and continued to fail until being set to at least 1. The only way I could achieve the value I wanted was to alter the NBT data during crafting. This does not make sense. If the value is valid on an item with custom NBT, it should also work on a regular item. The value is datapack driven and does in fact work but not if a datapack sets it as a default value.

I have included two datapacks for testing, labled with the repective values. Both also include a recipe for a test shotgun that has the projectile life set to 0.5 via custom NBT.

[test_life_1.zip](https://github.com/MrCrayfish/MrCrayfishGunMod/files/15450117/test_life_1.zip)
[test_life_0.5.zip](https://github.com/MrCrayfish/MrCrayfishGunMod/files/15450119/test_life_0.5.zip)

**Comment by MrCrayfish** [comment]
Not a bug, Life must be an whole number and positive.

**Comment by DaRealSparky** [comment]
Then how can it work with custom NBT?

**Comment by MrCrayfish** [comment]
It is likely rounded upon reading it.

**Comment by DaRealSparky** [comment]
Interesting. Thank You for your help.
