### ISSUE TITLE
Cant reload guns in 1.12.2

### ISSUE THREAD

**Issue by DrPlanecraft** [MrCrayfish/MrCrayfishGunMod#55]
I was playing a survival map when I noticed that I could not reload my guns or use your backpack mod

**Comment by MrCrayfish** [comment]
Check keybindings. You might have a conflict.

**Comment by darthvader45** [comment]
Made sure no conflicts, and had ammo.  Particularly happened with the minigun.

**Comment by ElCrackzito159** [comment]
Cant reload guns in 1.12.2,  check the keybindings and no :c, help

**Comment by etheslayer** [comment]
If you are playing a mod pack with MrCrayfishGunMod, make sure the ammo you have is the MrCrayfishGunMod ammo and not ammo from another mod.

**Comment by GovernedChair93** [comment]
same here i need help
