### ISSUE TITLE
Reload animation loop infinitely when there's no ammo

### ISSUE THREAD

**Issue by AtomicLugia** [MrCrayfish/MrCrayfishGunMod#57]
When I reload my gun and the remaining bullets are depleted while it's reloading, it keeps going, without adding any ammo. It stops when I switch to something different in the hotbar.

HOW TO REPRODUCE:
 - Empty a gun's ammo
 - Make sure that you have ammo as items left (but less than the capacity of the weapon)
 - Reload and wait until the ammo is depleted

MODS I USE:
Forge 14.23.5.2768
CustomNPCs 1.12
Varied Commodities 1.0
McCrayfish's Gun Mod 0.15.3
MrCrayfish's Furniture Mod 6.3.0
MrCrayfish's Vehicle Mod 0.43.4
WorldEdit 6.1.10-SNAPSHOT;3978-
Xaero's Minimap 20.7.1
Localized Weather & Storms 1.12.1-2.6.12
CoroUtil Library 1.12.1-1.2.37
Biomes O' Plenty 7.0.1
Obfuscate 0.4.2
XaeroMinimapCore 1.12.2-1.0

**Comment by 16-squared** [comment]
Might have been fixed over the course of the year.

**Comment by MrCrayfish** [comment]
I fixed it for newer versions of the mod, not 1.12.2 though
