### ISSUE TITLE
1.15.2 0.16.0 Heavy rifle doesn't accept ammo

### ISSUE THREAD

**Issue by WrongWeekend** [MrCrayfish/MrCrayfishGunMod#67]
The heavy rifle seems to be intended to accept advanced ammo but cannot be reloaded and is unusable. I have not tried the regular rifle, but given that both list their ammo type as "Air" in JEI i assume it has the same problem.

The pistol accepts basic ammo and can be used normally.

**Comment by MrCrayfish** [comment]
Fixed in 0.16.1
