### ISSUE TITLE
Firing bullets provokes neutral mobs

### ISSUE THREAD

**Issue by Inonedn** [MrCrayfish/MrCrayfishGunMod#68]

**Comment by ReXing007** [comment]
That's the problem I encountered just after installing the mod. You can use the silencer to reduce the effect radius. But in the end it's still there. My bees attacked me when I'm trying to protect my base even with the silencer. I hope neutral mobs can be excluded from this.

**Comment by noddynod443** [comment]
I have the same issue. This is especially a problem for me when trying to use the guard villager mod, since the village guards that I personally armed attack me when I fire a gun at an enemy mob.

**Comment by WrongWeekend** [comment]
The mod's config allows you to add additional entities to not be provoked by firing a gun nearby. By default only villagers are on the list. I was successfully able to add minecolonies citizens to the list, so it should work for any neutral mobs.

**Comment by noddynod443** [comment]
> The mod's config allows you to add additional entities to not be provoked by firing a gun nearby. By default only villagers are on the list. I was successfully able to add minecolonies citizens to the list, so it should work for any neutral mobs.

Where is the config file located?

**Comment by noddynod443** [comment]
> The mod's config allows you to add additional entities to not be provoked by firing a gun nearby. By default only villagers are on the list. I was successfully able to add minecolonies citizens to the list, so it should work for any neutral mobs.

Could you please show me how you added more mobs to the exempt aggro mob line? I tried adding "minecraft:cow" to the line as a test, but the cows are still acting panicked

**Comment by ReXing007** [comment]
What's the name of the config file?

**Comment by MrCrayfish** [comment]
I've made changes to only provoke hostile mobs. There is still exempt list in the config for any hostile mobs you don't want to become aggro. https://github.com/MrCrayfish/MrCrayfishGunMod/commit/c8a41c6b77200efb5a0d4068a6f1ace96e9ced26
