### ISSUE TITLE
1.15.2 0.16.1 No option to create bazooka rockets at workbench

### ISSUE THREAD

**Issue by WrongWeekend** [MrCrayfish/MrCrayfishGunMod#71]
The bazooka rocket does not appear in the list of items craftable at the workbench. Coincidentally, the x2 grenade recipe appears twice, with one recipe being more expensive than the other.

**Comment by noddynod443** [comment]
I've got the same issue.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishGunMod/commit/24b8d7d9b76a3c9fa0f5ede414ea1b3e37eb4ff6
