### ISSUE TITLE
Optifine and this mod causes OpenGL Error 1282

### ISSUE THREAD

**Issue by twoBn** [MrCrayfish/MrCrayfishGunMod#72]
at least i think its optifine because thats what another issue said. Every few seconds in the chat it says OpenGL Error: 1282 (Invalid Operation). Is there a fix?
![image](https://user-images.githubusercontent.com/60590727/86635498-259e6980-bfa1-11ea-925a-21ab04d3c525.png)

**Comment by twoBn** [comment]
yeah im getting the same issue as https://github.com/MrCrayfish/MrCrayfishGunMod/issues/53, the scope is black and not transparent

**Comment by SuperHarmony910** [comment]
I'm not sure if its this mod if it's causing this issue but it might be! Thanks for letting me know, hope this issue gets fixed in the latest update.

**Comment by MrCrayfish** [comment]
It's Optifine. It should stop if you disable shaders.

**Comment by SuperHarmony910** [comment]
ok thanks Cray!
