### ISSUE TITLE
Mod Version 1.16.1

### ISSUE THREAD

**Issue by Romaindu35** [MrCrayfish/MrCrayfishGunMod#73]
Hello,
Can you develop the mod in 1.16.1?
Romaindu35

**Comment by Romaindu35** [comment]
Why ?

**Comment by StefanH-AT** [comment]
Imagine closing issues without any comment and not porting your mod to the latest version

**Comment by MrCrayfish** [comment]
Imagine posting an already spammed suggestion on the *issue* tracker for the mod.
