### ISSUE TITLE
Creative tab icon displays a damage bar

### ISSUE THREAD

**Issue by WenXin20** [MrCrayfish/MrCrayfishGunMod#77]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Guns v0.16.1`

The creative tab icon displays a damage bar.
![2020-07-21_15 22 16](https://user-images.githubusercontent.com/12000593/88103902-3d601b00-cb67-11ea-8a0b-2d5a4eb8a258.png)

**Comment by MrCrayfish** [comment]
This has been fixed now
