### ISSUE TITLE
Z-fighting on Minigun in gui

### ISSUE THREAD

**Issue by WenXin20** [MrCrayfish/MrCrayfishGunMod#78]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Guns v0.16.1`

The minigun displays some z-fighting in the workbench gui.
![2020-07-21_15 28 51](https://user-images.githubusercontent.com/12000593/88104020-75fff480-cb67-11ea-8776-be81ac37a39c.png)

**Comment by MrCrayfish** [comment]
This has been fixed.
