### ISSUE TITLE
Hitbox of workbench is translated

### ISSUE THREAD

**Issue by WenXin20** [MrCrayfish/MrCrayfishGunMod#79]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Guns v0.16.1`

The hitbox of the workbench is translated on the y-axis about 1 pixel too high (Hitbox doesn't touch the ground).

![2020-07-21_15 34 19](https://user-images.githubusercontent.com/12000593/88104339-e9a20180-cb67-11ea-9be1-8eeba6f0b9ec.png)

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishGunMod/commit/32c97f12160375e0a84a425e20cff3b77999a659
Thanks for the report
