### ISSUE TITLE
Armor Clipping & Inanimate

### ISSUE THREAD

**Issue by MoodyBlueSkies** [MrCrayfish/MrCrayfishGunMod#83]
I was making a CrazyCraft server until I realized that my armor was clipping and inanimate like an armor stand with legs. My armor wouldn't move at all. It clips through my head, when I wear a helmet it inevitably clips through my head when I look at different angles. The armor doesn't move with my head, torso, legs, and boots, essentially an actual armor stand.

I started picking off mods one by one to find out which of the mods I installed was the one causing the problem. This took me 2 days to find but I found it, it's this MrCrayfishGunMod. 

With due respect, just informing. If there's a bug with the mod or with me, I need help if I want to include this mod in my CrazyCraft server.

This screenshot is just a small demonstration.
![Screenshot (53)](https://user-images.githubusercontent.com/69198251/89290467-92208d00-d661-11ea-804b-a90046a00467.png)

**Comment by MrCrayfish** [comment]
This is more likely a problem with Obfuscate, which in that case has been fixed in https://github.com/MrCrayfish/Obfuscate/commit/2c9f68f7ee0ebb0e40da51d82dd625c9b1d896ff
