### ISSUE TITLE
guns showing two models

### ISSUE THREAD

**Issue by zingygnu1323598** [MrCrayfish/MrCrayfishGunMod#85]
when i use the ar, or other two handed weapons, it shows two models

**Comment by willis1030** [comment]
when using these Galacticraft 1.12.2 mods (GalacticraftCore + Galacticraft-Planets + MicdoodleCore) it happened two  guns in hand and point to two direction.

**Comment by Orvngex** [comment]
is there any way to fix it without uninstalling any mods?

**Comment by MrCrayfish** [comment]
This is fixed in newer versions of the mod. I won't be patching for 1.12.2, critical bugs only.
