### ISSUE TITLE
[1.12.2] Disable the cooldown sword at the center of the screen when shooting

### ISSUE THREAD

**Issue by ExDomino** [MrCrayfish/MrCrayfishGunMod#91]
Hello, when you shoot with the gun, a big sword is shown at the center of the screen to indicate the cooldown you can shoot again. Is there a way to disable that?
There is aleady an indicator in the hotbar for that.
Thank you in advance.

**Comment by MrCrayfish** [comment]
I've added a config option int newer versions of the mod. Unfortuantely I no longer support the 1.12.2 version of this mod.
