### ISSUE TITLE
Grenades not making sound with the latest 1.15.2 version

### ISSUE THREAD

**Issue by 2Naato** [MrCrayfish/MrCrayfishGunMod#94]
In the latest 1.15.2 version of the mod, grenades do not make any sound when exploding (this is kinda annoying, we'd almost use them just for the fun sound sometimes).

This bug is both on client and server sides.
Note that if the player keeps the grenade on himself, it does makes noise → only when thrown (be it by hand or with the grenade launcher).
The explosion and damage seemed to work fine (it does seemed kinda strange without the sound tho, maybe you should check if this works as you intended it, whoever you are lmao → mr.crayfish or someone else ಠ‿ಠ).

_Note : The flashbang works fine._

So it would be nice if you fixed this little bug, because the rest works really well and the mod is REALLY cool (I'd use it with lycanites mobs, but it's too much laggy for my connexion on a server).

**Comment by MrCrayfish** [comment]
Closing since 1.15.2 isn't supported anymore
