### ISSUE TITLE
Cant reload any gun in 1.12.2

### ISSUE THREAD

**Issue by Mateusz7073** [MrCrayfish/MrCrayfishGunMod#96]
Im playing on a mod pack and I was testing this mod on creative... I had every kind of required ammo in inventory but reloading isnt working for some reason, even with changed keybind, it must be conflicting with another mod, but i cant tell with which :(

**Comment by MrCrayfish** [comment]
Duplicate of https://github.com/MrCrayfish/MrCrayfishGunMod/issues/39
