### ISSUE TITLE
Use a longer mod id

### ISSUE THREAD

**Issue by Jummit** [MrCrayfish/MrCrayfishGunMod#98]
The current mod id is "cgm". It's good practice to use longer ids, as they are more descriptive, easier to read and are less prone to namespace conflicts.
I would suggest an id like "crayfishgunmod" or "craygunmod".

**Comment by MrCrayfish** [comment]
It's too late now. Not saying I like it either, just wasn't as experienced back when I first created the mod. Unless a mod actually conflicts, I wouldn't worry.

**Comment by Jummit** [comment]
> It's too late now. Not saying I like it either, just wasn't as experienced back when I first created the mod. Unless a mod actually conflicts, I wouldn't worry.

Yeah, that's fair. Thanks for the amazing mod btw!
