### ISSUE TITLE
Creative tab item has a durability bar

### ISSUE THREAD

**Issue by Jummit** [MrCrayfish/MrCrayfishGunMod#99]
There is a black durability under the weapon item in the creative tab:

![image](https://user-images.githubusercontent.com/28286961/101979509-e665fa00-3c5d-11eb-96ce-a1de8bfe76fa.png)

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishGunMod/commit/80e1a8144a8549ec57487f4c255cab2918076ff8
